/**
 * 中文常量
 * @type String
 */
var LANGUAGE_CN = {
	/*********************系统常量 start******************/
	COM_SYS_BASICPLAT : '基础平台',
	COM_SYS_DOCMANAGE : '文档管理',
	COM_SYS_DOCSAFE : '文档安全',
	COM_SYS_PSM : '打印安全',
	COM_SYS_MDM : '移动端安全',
	COM_SYS_BAK : '备份管理',
	COM_SYS_MENU : '功能菜单',
	COM_SYS_HELLO : '您好，',
	COM_SYS_EDIT_PASSWARD : '修改密码',
	COM_SYS_OLD_PASSWARD : '旧密码',
	COM_SYS_NEW_PASSWARD : '新密码',
	COM_SYS_RE_PASSWARD : '重复新密码',
	COM_SYS_DIFFERENT_PASS : '请正确输入新密码及重复新密码！',
	COM_SYS_SIMPLE_PASS : '密码复杂度不够，请重新设置！',
	COM_SYS_SAME_PASS : '新密码不能与旧密码一致，请重新设置！',
	COM_SYS_QUIT : '退出系统',
	COM_SYS_LOGIN_BUTTON:'登<span style="margin-left:30px"></span>录',
	COM_SYS_QUIT_SYSTEM : '您是否确认退出？',
	COM_SYS_LOGIN:'用户登录',
	COM_SYS_COMPANY:'Copyright@crma',
	COM_SYS_TIPS_USERNAME:'用户名不能为空！',
	COM_SYS_TIPS_PASSWORD:'密码不能为空！',
	COM_SYS_TIPS_VALIDATE:'验证码不能为空！',
	COM_SYS_LOGIN_FAILURE:'登录失败！',
	COM_SYS_SYSTEM_ERROR : '系统错误！',
	COM_SYS_LOGIN_STATE_LOCK : '账号锁定！',
	COM_SYS_LOGIN_STATE_LOGOUT : '账号注销！',
	COM_SYS_LOGIN_STATE_OVERDUE : '账号过期！',
	COM_SYS_LOGIN_STATE_PWD_ERROR : '密码错误！',
	COM_SYS_LOGIN_STATE_VALIDATE_ERROR : '验证码错误！',
	COM_SYS_LOGIN_STATE_PASSWORD_COUNT_ERROR : '密码输错已超过5次，请30分钟后再登录！',
	COM_SYS_LOGIN_NO_ANTHORITY : '没有权限登录！',
	COM_SYS_LOGIN_STATE_NOT_EXIT : '用户名不存在！',
	COM_SYS_QUERY_DATA : '请稍候...',
	COM_SYS_LOAD_DATA : '正在加载，请稍候...',
	COM_SYS_SAVE_DATA : '正在保存，请稍候...',
	/*********************系统常量 end*******************/
	
	/*********************通用型常量 start******************/
	DGS_COMM_TIPS : '提示',
	DGS_COMM_TIPS_EXPLAIN : '说明',
	DGS_COMM_DEFAULT_SUCCESS_MSG : "操作成功",
	DGS_COMM_DELETE_SUCCESS : '删除成功',	
	DGS_COMM_UNSELECTION_ERROR : '未选择',
	DGS_COMM_MULTISELECTION_ERROR : '只能选择一条记录',
	DGS_COMM_QUICK_SEARCH : '快速检索',
	DGS_COMM_EXPAND_ALL : '全部展开',
	DGS_COMM_COLLAPSE_ALL : '全部收缩',
	DGS_COMM_ADD : '新增',
	DGS_COMM_MODIFY : '修改',
	DGS_COMM_VIEW : '查看',
	DGS_COMM_COPY : '复制',
	DGS_COMM_MOVE : '移动',
	DGS_COMM_ISDELETE : '是否确认删除？',
	DGS_COMM_DISPLAY_MSG : '显示第 {0} 条到 {1} 条记录,一共 {2} 条',
	DGS_COMM_EMPTY_MSG : '没有符合条件的记录',
	DGS_COMM_DISPLAY_MSG1 : '第{0}-{1}条,共{2}条',
	DGS_COMM_EMPTY_MSG1 : '没有记录',
	DGS_COMM_TIMEOUT : '会话超时，请重新登录！',
	DGS_COMM_HAS_SESSION : '已有其他用户登录，请重新登录!',
	DGS_COMM_PAGE10 : '10条/页',
	DGS_COMM_PAGE20 : '20条/页',
	DGS_COMM_PAGE50 : '50条/页',
	DGS_COMM_PAGE100 : '100条/页',
	DGS_COMM_NOT_NULL : '必填项不可以为空格！',
	DGS_COMM_NO_SPECIAL_CHARACTER : '不可以输入特殊字符！',
	DGS_COMM_DELETE_TEMPLATE : '模板已被应用，不可删除！',
	/*********************通用型常量 end*******************/
	
	/*********************通用按钮常量 start******************/
	DGS_BUTTON_ADD : '新增',
	DGS_BUTTON_MODIFY : '修改',
	DGS_BUTTON_DELETE : '删除',
	DGS_BUTTON_VIEW : '查看',
	DGS_BUTTON_SEARCH : '查询',
	DGS_BUTTON_ADVANCED_SEARCH : '高级查询',
	DGS_BUTTON_SEARCH_ALL : '查询全部',
	DGS_BUTTON_REFRESH : '刷新',
	DGS_BUTTON_ENSURE : '确定',
	DGS_BUTTON_CANCEL : '取消',
	DGS_BUTTON_SUBMIT : '提交',
	DGS_BUTTON_SAVE : '保存',
	DGS_BUTTON_RESET : '重置',
	DGS_BUTTON_CLOSE : '关闭',
	DGS_BUTTON_EMPTY : '清空',
	DGS_BUTTON_IMPORT : '导入',
	DGS_BUTTON_RECOVERY : '恢复',
	DGS_BUTTON_EXPORT : '导出',
	DGS_BUTTON_COPY : '复制',
	DGS_BUTTON_START : '启用',
	DGS_BUTTON_SHUTDOWN : '停止',
	DGS_BUTTON_EXPORT_SUMMARY : '导出汇总',
	/*********************通用按钮常量 end*******************/
	
	/*********************通用操作日志 start******************/
	DGS_COMM_OPERATOR_LOG_NAME : '操作人',
	DGS_COMM_OPERATOR_LOG_IP : '操作IP',
	DGS_COMM_OPERATOR_LOG_MODULE_NAME : '操作模块',
	DGS_COMM_OPERATOR_LOG_TIME : '操作时间',
	DGS_COMM_OPERATOR_LOG_CONTENT : '操作内容',
	DGS_COMM_OPERATOR_LOG_FILEPATH : '文件路径',
	DGS_COMM_OPERATOR_LOG_REMARK : '备注',
	DGS_COMM_OPERATOR_LOG_START_TIME : '操作时间起',
	DGS_COMM_OPERATOR_LOG_END_TIME : '操作时间止',
	DGS_COMM_OPERATOR_LOG_STATE : '状态',
	DGS_COMM_OPERATOR_LOG_SUCCESS : '成功',
	DGS_COMM_OPERATOR_LOG_FAILURE : '失败',
	DGS_COMM_OPERATOR_LOG_SELECT_ONE : '只能选择一条日志',
	DGS_COMM_OPERATOR_LOG_TIPS_DISPLAY:'查看',
	DGS_COMM_OPERATOR_LOG_DATE_ERROR : '起始日期不能大于截止日期！',
	/*********************通用操作日志 end******************/
	
	/*********************TAB关闭按钮 start******************/
	DGS_MENU_CLOSE_ALL : '关闭所有标签',
	DGS_MENU_CLOSE_OTHERS : '关闭其他标签',
	DGS_MENU_CLOSE : '关闭此标签',
	/*********************TAB关闭按钮 end*******************/
	
	/*********************组织机构管理 start******************/
	DGS_ORGANIZATION_TITLE : '组织机构管理',
	DGS_ORGANIZATION_ROOT :'组织机构',
	DGS_ORGANIZATION_TIPS_NAME : '请输入名称',
	DGS_ORGANIZATION_TIELD_NAME : '名称',
	DGS_ORGANIZATION_TIELD_LEGALPERSON : '法人代表',
	DGS_ORGANIZATION_TIELD_ESTABLISHMENT_TIME : '成立日期',
	DGS_ORGANIZATION_TIELD_CREATOR_NAME : '创建人',
	DGS_ORGANIZATION_DELETE_HAS_CHILD:'有子组织或部门，无法删除',
	DGS_ORGANIZATION_DELETE_HAS_USER:'组织部门下有用户，无法删除',
	//组织
	DGS_ORGANIZATION_ORG_TITLE_ADD:'新增组织',
	DGS_ORGANIZATION_ORG_TITLE_EDIT:'修改组织信息',
	DGS_ORGANIZATION_ORG_TITLE_DISPLAY:'查看组织信息',
	DGS_ORGANIZATION_ORG_FULLNAME:'组织全称',
	DGS_ORGANIZATION_ORG_SHORTNAME:'组织简称',
	DGS_ORGANIZATION_ORG_PARENTID:'上级组织',
	DGS_ORGANIZATION_ORG_LEGALPERSON:'法人代表',
	DGS_ORGANIZATION_ORG_ESTABLISHIMENTTIME:'成立时间',
	DGS_ORGANIZATION_ORG_PHONE:'电话号码',
	DGS_ORGANIZATION_ORG_FAX:'传真',
	DGS_ORGANIZATION_ORG_EMAIL:'电子邮件',
	DGS_ORGANIZATION_ORG_WEB:'网址',
	DGS_ORGANIZATION_ORG_ADDRESS:'地址',
	DGS_ORGANIZATION_ORG_PORFILE:'组织简介',
	DGS_ORGANIZATION_ORG_REMARK:'备注',
	DGS_ORGANIZATION_ORG_EXITS:'组织已存在！',
	DGS_ORGANIZATION_ORG_TIPS : '请选择组织！',
	//部门
	DGS_ORGANIZATION_DEPT_TITLE_ADD:'新增部门',
	DGS_ORGANIZATION_DEPT_TITLE_EDIT:'修改部门信息',
	DGS_ORGANIZATION_DEPT_TITLE_DISPLAY:'查看部门信息',
	DGS_ORGANIZATION_DEPT_NAME:'部门名称',
	DGS_ORGANIZATION_DEPT_CODE:'部门编号',
	DGS_ORGANIZATION_DEPT_PARENTID:'上级组织',
	DGS_ORGANIZATION_DEPT_ESTABLISHIMENTTIME:'成立时间',
	DGS_ORGANIZATION_DEPT_HEAD:'部门负责人',
	DGS_ORGANIZATION_DEPT_HEADPHONE:'负责人电话',
	DGS_ORGANIZATION_DEPT_CONTACT:'部门联系人',
	DGS_ORGANIZATION_DEPT_CONTACTPHONE:'联系人电话',
	DGS_ORGANIZATION_DEPT_DEPT:'部门职责',
	DGS_ORGANIZATION_DEPT_REMARK:'备注',
	DGS_ORGANIZATION_DEPT_EXITS:'部门已存在！',
	DGS_ORGANIZATION_DEPT_TIPS : '请选择部门！',
	/*********************组织机构管理 end*******************/
	
	/*********************用户管理 start*******************/
	DGS_USERMANAGEMENT_TIPS_ACCOUNTORNAME : '请输入账号或姓名',
	DGS_USERMANAGEMENT_BUTTON_INIT_PASSWORD : '初始化密码',
	DGS_USERMANAGEMENT_IS_INIT_PASSWORD : '是否确认初始化密码？',
	DGS_USERMANAGEMENT_INITPASSWORD_SUCCESS : '初始化密码成功',
	DGS_USERMANAGEMENT_BUTTON_DEPART_CHANGE : '部门用户转移',
	DGS_USERMANAGEMENT_UNSELECT_DEPARMENT:'未选择部门或组织',
	DGS_USERMANAGEMENT_EXITS_DEPARMENT:'该节点下有组织部门，不能转移',
	DGS_USERMANAGEMENT_FIELD_NAME : '姓名',
	DGS_USERMANAGEMENT_TIPS_ADD : '新增用户',
	DGS_USERMANAGEMENT_TIPS_EDIT : '修改用户信息',
	DGS_USERMANAGEMENT_TIPS_DISPLAY : '查看用户信息',
	DGS_USERMANAGEMENT_ACCOUNT : '账号',
	DGS_USERMANAGEMENT_FULLNAME : '姓名',
	DGS_USERMANAGEMENT_ALIAS : '别名',
	DGS_USERMANAGEMENT_SEX : '性别',
	DGS_USERMANAGEMENT_SEX1 : '女',
	DGS_USERMANAGEMENT_SEX2 : '男',
	DGS_USERMANAGEMENT_MOBILPHONE : '手机',
	DGS_USERMANAGEMENT_PHONE : '固定电话',
	DGS_USERMANAGEMENT_EMAIL : '邮箱账号',
	DGS_USERMANAGEMENT_ADDRESS : '家庭地址',
	DGS_USERMANAGEMENT_LOGOUT : '允许注销',
	DGS_USERMANAGEMENT_LOGOUT1 : '是',
	DGS_USERMANAGEMENT_LOGOUT0 : '否',
	DGS_USERMANAGEMENT_STATE : '账号状态',
	DGS_USERMANAGEMENT_STATE1 : '激活',
	DGS_USERMANAGEMENT_STATE2 : '锁定',
	DGS_USERMANAGEMENT_JOBLEVEL : '岗级',
	DGS_USERMANAGEMENT_PARENTID : '所属部门',
	DGS_USERMANAGEMENT_SECURITY_CLASSIFICATION : '密级',
	DGS_USERMANAGEMENT_DEGRADE : '允许降级',
	DGS_USERMANAGEMENT_DEGRADE1 : '是',
	DGS_USERMANAGEMENT_DEGRADE0 : '否',
	DGS_USERMANAGEMENT_EXTENDS_DEPART_FD_TEMPLATE: '继承外发策略',
	DGS_USERMANAGEMENT_EXTENDS_DEPART_FD_TEMPLATE1 : '是',
	DGS_USERMANAGEMENT_EXTENDS_DEPART_FD_TEMPLATE0 : '否',
	DGS_USERMANAGEMENT_CHANGE : '转移至',
	DGS_USERMANAGEMENT_CHANGESUCESS : '用户转移成功!',
	DGS_USERMANAGEMENT_REMARKS : '备注',
	DGS_USERMANAGEMENT_EXITS : '账号已存在',
	DGS_USERMANAGEMENT_SUSER_UNDELETE : '系统内置用户不能删除',
	DGS_USERMANAGEMENT_SUSER_UNEDIT : '系统内置用户不能修改',
	DGS_USERMANAGEMENT_SUSER_UNINITPASSWORD : '系统内置用户不能手动初始化密码',
	DGS_USERMANAGEMENT_SELF_UNDELETE : '不能删除当前登录用户',
	DGS_USERMANAGEMENT_SELECT_ONE : '只能选择一个用户',
	DGS_USERMANAGEMENT_TEMPLATENAME : '应用模板',
	DGS_USERMANAGEMENT_SMTP : '邮箱服务器',
	DGS_USERMANAGEMENT_SMTP_PORT : '端口',
	DGS_USERMANAGEMENT_EMAIL_PASSWORD : '邮箱密码',
	DGS_USERMANAGEMENT_EMAIL_TYPE : '邮箱服务器类型',
	DGS_USERMANAGEMENT_EMAIL_TYPE0 : 'smtp',
	DGS_USERMANAGEMENT_EMAIL_TYPE1 : 'exchange',
	/*********************用户管理 end********************/
	
	/*********************角色管理 start******************/
	DGS_ROLEMANAGEMENT_NAME : '名称',
	DGS_ROLEMANAGEMENT_TYPE : '类型',
	DGS_ROLEMANAGEMENT_DEPT : '职能',
	DGS_ROLEMANAGEMENT_REMARK : '备注',
	DGS_ROLEMANAGEMENT_AUTHS:'权限',
	DGS_ROLEMANAGEMENT_TIPS_SEARCH : '请输入角色名称',
	DGS_ROLEMANAGEMENT_TIPS_ADD : '新增角色',
	DGS_ROLEMANAGEMENT_TIPS_EDIT : '修改角色信息',
	DGS_ROLEMANAGEMENT_TIPS_DISPLAY : '查看角色信息',
	DGS_ROLEMANAGEMENT_DISTRIBUTE_USER : '分配用户',
	DGS_ROLEMANAGEMENT_DISTRIBUTE_USER_TIPS : '说明：双击左边表格中用户，或选中后点击分配按钮，可进行分配；单击右边表格中用户的删除图标，可撤销分配。',
	DGS_ROLEMANAGEMENT_USER_NAME : '姓名',
	DGS_ROLEMANAGEMENT_USER_ACCOUNT : '账号',
	DGS_ROLEMANAGEMENT_USER_SEX : '性别',
	DGS_ROLEMANAGEMENT_SUSER_UNEDIT : '系统内置角色，无法修改',
	DGS_ROLEMANAGEMENT_SUSER_UNDELETE : '系统内置角色，无法删除',
	DGS_ROLEMANAGEMENT_USER_DEPT : '所属部门',
	DGS_ROLEMANAGEMENT_IS_SELECT : '是否选中',
	DGS_ROLEMANAGEMENT_ASSIGNED_USER : '已分配用户',
	DGS_ROLEMANAGEMENT_NOT_ASSIGNED_USER : '待分配用户',
	DGS_ROLEMANAGEMENT_DEPT_TIPS : '请选择部门',
	DGS_ROLEMANAGEMENT_MAME_TIPS : '请输入账号或姓名',
	DGS_ROLEMANAGEMENT_BUTTON_DISTRIBUTE : '分配',
	DGS_ROLEMANAGEMENT_HANDLE : '操作',
	DGS_ROLEMANAGEMENT_SELECT_ONE : '只能选择一个角色',
	DGS_ROLEMANAGEMENT_EXITS : '该角色已存在！',
	/*********************角色管理 end********************/
	
	/*********************权限管理 start******************/
	DGS_AUTH_NAME:'名称',
	DGS_AUTH_CREATOR_NAME : '创建人',
	DGS_AUTH_CREATOR_TIME : '创建时间',
	DGS_AUTH_REMARK : '备注',
	DGS_AUTH_BASICINFO : '基本信息',
	DGS_AUTH_TREE_TITLE : '功能树',
	DGS_AUTH_TIPS_AUTHORIZE : '请授权！',
	DGS_AUTH_BUTTON_DISTRIBUTE_ROLE : '分配角色',
	DGS_AUTH_EXITS : '权限已存在！',
	DGS_AUTH_TIPS_NAME : '请输入权限名称',
	DGS_AUTH_DISTRIBUTE_ROLE : '分配角色',
	DGS_AUTH_DISTRIBUTE_ROLE_TIPS : '双击未分配角色，即可执行分配动作。',
	DGS_AUTH_ROLE_TREE : '角色树',
	DGS_AUTH_ROLE_NAME : '角色名称',
	DGS_AUTH_HANDLE : '操作',
	DGS_AUTH_ASSIGNED_ROLE : '已分配角色',
	DGS_AUTH_IS_SYSTEM_MODIFY : '系统内置权限，不可修改！',
	DGS_AUTH_IS_SYSTEM_DELETE : '系统内置权限，不可删除！',
	DGS_AUTH_SELECT_ONE : '只能选择一个权限',
	/*********************权限管理 end******************/
	
	/*********************终端升级 start******************/
	DGS_CLIENTPATCH_NAME:'名称',
	DGS_CLIENTPATCH_VERSION : '版本',
	DGS_CLIENTPATCH_HASH : 'md5值',
	DGS_CLIENTPATCH_SIZE : '大小',
	DGS_CLIENTPATCH_TYPE : '类型',
	DGS_CLIENTPATCH_CLIENTPATCH : '终端升级',
	DGS_CLIENTPATCH_PATCHNAMESTYLE : '升级包的格式为DGS V1.1.1.20150812.7z',
	DGS_CLIENTPATCH_PATCHNAMESTYLEERROR : '升级包格式不正确',
	DGS_CLIENTPATCH_SELECT_ONE : '只能选择一条记录',
	DGS_CLIENTPATCH_IS_MANUAL : '手动设置',
	DGS_CLIENTPATCH_UPGRADE_SETTING : '升级包应用',
	DGS_CLIENTPATCH_SELECT_ALL : '全选',
	DGS_CLIENTPATCH_APPLY_CHILD : '应用到子项',
	DGS_CLIENTPATCH_SEARCH_TIP : '请输入名称',
	DGS_CLIENTPATCH_SEARCH_ALL : '查询全部',
	DGS_CLIENTPATCH_NOT_SETTING : '升级包导入时未设置手动配置！',
	/*********************终端升级 end******************/
	
	
	/*********************DM模块名称 start******************/
	DM_TAB_DOC : '文档',
	DM_TAB_SEARCH : '搜索',
	DM_MENU_CLASSIC_DOC : '分类文件库',
	DM_MENU_TOP_LABEL : '热门标签',
	DM_MENU_MY_DOC : '我的文档',
	DM_MENU_PERSONAL_FAVORITES : '个人收藏夹',
	DM_MENU_WORK_DOCUMENT : '工作文档',
	DM_MENU_RECYCLE : '回收站',
	DM_MENU_FILE_RECORD : '审批记录',
	DM_MENU_APPLICATION_RECORD : '申请记录',
	DM_MENU_CAPTURER_EGISTER : '捕获登记',
	/*********************DM模块名称 end******************/
	
	/*********************用户组管理 start******************/
	DGS_USERGROUP_DISTRIBUTE_USER : '分配用户',
	DGS_USERGROUP_TIPS_NAME : '请输入用户组名称',
	DGS_USERGROUP_TIPS_ADD : '新增用户组',
	DGS_USERGROUP_TIPS_EDIT : '修改用户组',
	DGS_USERGROUP_TIPS_DISPLAY : '查看用户组',
	DGS_USERGROUP_EXITS : '用户组已存在',
	DGS_USERGROUP_NAME : '用户组名称',
	DGS_USERGROUP_REMARK : '备注',
	DGS_USERGROUP_SELECT_ONE : '只能选择一个用户组',
	DGS_USERGROUP_DISTRIBUTE_USER_TIPS : '说明：双击左边表格中用户，或选中后点击分配按钮，可进行分配；单击右边表格中用户的删除图标，可撤销分配。',
	DGS_USERGROUP_DEPT_TIPS : '请选择部门',
	DGS_USERGROUP_DEPT_SELECT : '请选择组织或部门',
	DGS_USERGROUP_MAME_TIPS : '请输入账号或姓名',
	DGS_USERGROUP_BUTTON_DISTRIBUTE : '分配',
	DGS_USERGROUP_USER_ACCOUNT : '账号',
	DGS_USERGROUP_USER_NAME : '姓名',
	DGS_USERGROUP_USER_DEPT : '所属部门',
	DGS_USERGROUP_IS_SELECT : '是否选中',
	DGS_USERGROUP_HANDLE : '操作',
	DGS_USERGROUP_REMARK : '备注',
	DGS_USERGROUP_GROUPINGUSER_SELECT_ALL : '查询全部',
	/*********************用户组管理 end******************/
	
	/*********************系统配置 start******************/
	COM_SYSTEMSET_BUTTON_SAVE : '保存',
	COM_SYSTEMSET_UPLOAD_PATH : '文档库存储路径',
	COM_SYSTEMSET_FD_PATH : '文档安全存储路径',
	COM_SYSTEMSET_BASE_PATH : '基础存储路径',
	COM_SYSTEMSET_PREVIEW_PATH : '预览存储路径',
	COM_SYSTEMSET_ACL_POOL_SIZE : 'ACL线程池大小',
	COM_SYSTEMSET_TIKA_POOL_SIZE : 'tika线程池大小',
	COM_SYSTEMSET_PREVIEW_POOL_SIZE : '预览线程池大小',
	COM_SYSTEMSET_SOLR_PATH : 'OWA服务地址',
	COM_SYSTEMSET_BASE_REMARK : '(用于存放升级包)',
	COM_SYSTEMSET_UPLOAD_REMARK : '(用于存放上传的文件)',
	COM_SYSTEMSET_PREVIEW_REMARK : '(用于存放预览时转换的临时文件)',
	COM_SYSTEMSET_FD_REMARK : '(用于存放外发文件)',
	COM_SYSTEMSET_SOLR_REMARK : '(office app server服务器地址，用于预览文档)',
	COM_SYSTEMSET_SAVE_SUCCESS_TIP : '操作成功！<br/>如果当前是集群部署，则需要重启服务器方能生效！',
	COM_SYSTEMSET_TIP : '注：若所配置的路径是本地路径，不可以配置双斜杠，正确示例：d:\\fdFile，错误示例：d:\\\\fdFile',
	COM_SYSTEMSET_SERVER_POOL : '服务器池',
	COM_SYSTEMSET_SERVER_POOL_REMARK : '(多个服务器地址以;隔开，一般配置两个地址：主备或内外。)',
	COM_SYSTEMSET_MODIFY_PASSWORD :'允许强制修改密码',
	COM_SYSTEMSET_MODIFY_PASSWORD_YES :'是',
	COM_SYSTEMSET_MODIFY_PASSWORD_NO :'否',
	COM_SYSTEMSET_MODIFY_PASSWORD_REMARK :'(配置客户端是否需要在首次登录时强制修改密码)',
	COM_SYSTEMSET_DLPSERVER : 'DLP服务地址',
	COM_SYSTEMSET_DLPSERVER_REMARK : '(DLP服务器域名（IP）及端口，如http://192.168.1.100:8080，客户端需要能连接到此地址)',
	COM_SYSTEMSET_PSM_PATH : 'PSM存储路径',
	COM_SYSTEMSET_PSM_PATH_REMARK : '(用于存放打印文件)',
	COM_SYSTEMSET_PSM_SERVER : 'PSM服务地址',
	COM_SYSTEMSET_PSM_SERVER_REMARK : '(PSM服务器域名（IP）及端口，如http://192.168.1.100:8080，客户端需要能连接到此地址)',
	COM_SYSTEMSET_BAK_SERVER : 'BAK服务地址',
	COM_SYSTEMSET_BAK_SERVER_REMARK : '(BAK服务器域名（IP）及端口，如http://192.168.1.100:8080，客户端需要能连接到此地址)',
	/*********************系统配置 end********************/
	
	/*********************评论 start******************/
	DM_COMMENT_TITLE : '评论',
	DM_COMMENT_TEXT_CREATOR : '评论人',
	DM_COMMENT_TEXT_START_TIME : '评论时间起',
	DM_COMMENT_TEXT_END_TIME : '评论时间止',
	DM_COMMENT_TEXT_DOC_NAME : '文档',
	DM_COMMENT_TEXT_CONTENT : '评论内容',
	DM_COMMENT_TEXT_CREATE_TIME : '评论时间',
	DM_COMMENT_TEXT_DOC : '评论的文档',
	DM_COMMENT_TEXT_GRADE : '评分',
	DM_COMMENT_TEXT_COMMENT : '评论',
	DM_COMMENT_SELECT_ONE : '只能选择一个评论！',
	DM_COMMENT_EXCUTE_RATE : '评分...',
	DM_COMMENT_RATE_BAD : '较差',
	DM_COMMENT_RATE_NOTBAD : '还可以',
	DM_COMMENT_RATE_OK : '好',
	DM_COMMENT_RATE_BETTER : '相当好',
	DM_COMMENT_RATE_PERFECT : '好极了',
	DM_COMMENT_RATE_RESULT : '评分结果！',
	DM_COMMENT_GRADE_UNIT : '分',
	DM_COMMENT_DATE_ERROR : '起始日期不能大于截止日期！',
	/*********************评论 end******************/
}



