/**
 * 英文常量
 * @type String
 */
var LANGUAGE_US = {
	/*********************系统常量 start******************/
	DGS_SYS_BASICPLAT : 'Basic Plat',//'基础平台',
	DGS_SYS_DOCMANAGE : 'DM',//'文档库管理',
	DGS_SYS_DOCSAFE : 'DG',//'文档安全',
	DGS_SYS_MENU : 'Menu',//'功能菜单',
	DGS_SYS_HELLO : 'Hello,',//'您好，',
	DGS_SYS_EDIT_PASSWARD : 'Edit Passward',//'修改密码',
	DGS_SYS_OLD_PASSWARD : 'Old Passward',//'旧密码',
	DGS_SYS_NEW_PASSWARD : 'New Passward',//'新密码',
	DGS_SYS_RE_PASSWARD : 'Repeat Password',//'重复新密码',
	DGS_SYS_DIFFERENT_PASS : '请正确输入新密码及重复新密码！',
	DGS_SYS_SIMPLE_PASS : '密码复杂度不够，请重新设置！',
	DGS_SYS_SAME_PASS : '新密码不能与旧密码一致，请重新设置！',
	DGS_SYS_QUIT : 'Quit',//'退出系统',
	DGS_SYS_LOGIN_BUTTON:'LOGIN',//'登<span style="margin-left:30px"></span>录',
	DGS_SYS_QUIT_SYSTEM : '您是否确认退出？',
	DGS_SYS_LOGIN:'User Login',//'用户登录',
	DGS_SYS_COMPANY:'Copyright©江苏敏捷科技股份有限公司',
	DGS_SYS_TIPS_USERNAME:'用户名不能为空！',
	DGS_SYS_TIPS_PASSWORD:'密码不能为空！',
	DGS_SYS_LOGIN_FAILURE:'登录失败！',
	DGS_SYS_SYSTEM_ERROR : '系统错误！',
	DGS_SYS_LOGIN_STATE_LOCK : '账号锁定！',
	DGS_SYS_LOGIN_STATE_LOGOUT : '账号注销！',
	DGS_SYS_LOGIN_STATE_OVERDUE : '账号过期！',
	DGS_SYS_LOGIN_STATE_PWD_ERROR : 'Passward Error!',//'密码错误！',
	DGS_SYS_LOGIN_NO_ANTHORITY : '没有权限登录！',
	DGS_SYS_LOGIN_STATE_NOT_EXIT : '用户名不存在！',
	DGS_SYS_QUERY_DATA : 'Please Wait...',//'请稍候...',
	/*********************系统常量 end*******************/
	
	/*********************通用型常量 start******************/
	DGS_COMM_TIPS : 'TIPS',//'提示',
	DGS_COMM_DEFAULT_SUCCESS_MSG : 'Success',//"操作成功",
	DGS_COMM_DELETE_SUCCESS : 'Delete Success',//'删除成功',	
	DGS_COMM_UNSELECTION_ERROR : '未选择',
	DGS_COMM_MULTISELECTION_ERROR : '只能选择一条记录',
	DGS_COMM_QUICK_SEARCH : '快速检索',
	DGS_COMM_EXPAND_ALL : '全部展开',
	DGS_COMM_COLLAPSE_ALL : '全部收缩',
	DGS_COMM_ADD : 'Add',//'新增',
	DGS_COMM_MODIFY : 'Modify',//'修改',
	DGS_COMM_VIEW : 'View',//'查看',
	DGS_COMM_MOVE : 'Move',//'移动',
	DGS_COMM_ISDELETE : '是否确认删除？',
	DGS_COMM_DISPLAY_MSG : '显示第 {0} 条到 {1} 条记录,一共 {2} 条',
	DGS_COMM_EMPTY_MSG : '没有符合条件的记录',
	DGS_COMM_DISPLAY_MSG1 : '第{0}-{1}条,共{2}条',
	DGS_COMM_EMPTY_MSG1 : '没有记录',
	DGS_COMM_TIMEOUT : '会话超时，请重新登录！',
	DGS_COMM_HAS_SESSION : '已有其他用户登录，请重新登录!',
	DGS_COMM_PAGE10 : '10条/页',
	DGS_COMM_PAGE20 : '20条/页',
	DGS_COMM_PAGE50 : '50条/页',
	DGS_COMM_PAGE100 : '100条/页',
	DGS_COMM_NOT_NULL : '必填项不可以为空格！',
	DGS_COMM_NO_SPECIAL_CHARACTER : '不可以输入特殊字符！',
	DGS_COMM_DELETE_TEMPLATE : '模板已被应用，是否确认删除？',
	/*********************通用型常量 end*******************/
	
	/*********************通用按钮常量 start******************/
	DGS_BUTTON_ADD : 'Add',//'新增',
	DGS_BUTTON_MODIFY : 'Modify',//'修改',
	DGS_BUTTON_DELETE : 'Delete',//'删除',
	DGS_BUTTON_VIEW : 'View',//'查看',
	DGS_BUTTON_SEARCH : 'Search',//'查询',
	DGS_BUTTON_SEARCH_ALL : 'Search all',//'查询全部',
	DGS_BUTTON_REFRESH : 'Refresh',//'刷新',
	DGS_BUTTON_ENSURE : 'Ensure',//'确定',
	DGS_BUTTON_CANCEL : 'Cancel',//'取消',
	DGS_BUTTON_SUBMIT : 'Submit',//'提交',
	DGS_BUTTON_SAVE : 'Save',//'保存',
	DGS_BUTTON_RESET:'Reset',//'重置',
	DGS_BUTTON_CLOSE:'Close',//'关闭',
	DGS_BUTTON_EMPTY : 'Empty',//'清空',
	DGS_BUTTON_IMPORTPATCH:'Import',//'导入',
	DGS_BUTTON_DELECTPATCH:'Delete',//'删除',
	DGS_BUTTON_RECOVERY : 'Recovery',//'恢复',
	/*********************通用按钮常量 end*******************/
	
	/*********************TAB关闭按钮 start******************/
	DGS_MENU_CLOSE_ALL : 'Close All',//'关闭所有标签',
	DGS_MENU_CLOSE_OTHERS : 'Close Others',//'关闭其他标签',
	DGS_MENU_CLOSE : 'Close',//'关闭此标签',
	/*********************TAB关闭按钮 end*******************/
	
	/*********************组织机构管理 start******************/
	DGS_ORGANIZATION_TITLE : 'Organization Manage',//'组织机构管理',
	DGS_ORGANIZATION_ROOT :'Organization',//'组织机构',
	DGS_ORGANIZATION_TIPS_NAME : 'Enter Name',//'请输入名称',
	DGS_ORGANIZATION_TIELD_NAME : 'Name',//'名称',
	DGS_ORGANIZATION_TIELD_LEGALPERSON : '法人代表',
	DGS_ORGANIZATION_TIELD_ESTABLISHMENT_TIME : '成立日期',
	DGS_ORGANIZATION_TIELD_CREATOR_NAME : '创建人',
	DGS_ORGANIZATION_DELETE_HAS_CHILD:'有子组织或部门，无法删除',
	DGS_ORGANIZATION_DELETE_HAS_USER:'组织部门下有用户，无法删除',
	//组织
	DGS_ORGANIZATION_ORG_TITLE_ADD:'Add Orga',//'新增组织',
	DGS_ORGANIZATION_ORG_TITLE_EDIT:'Modify Orga',//'修改组织信息',
	DGS_ORGANIZATION_ORG_TITLE_DISPLAY:'View Orga',//'查看组织信息',
	DGS_ORGANIZATION_ORG_FULLNAME:'组织全称',
	DGS_ORGANIZATION_ORG_SHORTNAME:'组织简称',
	DGS_ORGANIZATION_ORG_PARENTID:'上级组织',
	DGS_ORGANIZATION_ORG_LEGALPERSON:'法人代表',
	DGS_ORGANIZATION_ORG_ESTABLISHIMENTTIME:'成立时间',
	DGS_ORGANIZATION_ORG_PHONE:'Phone',//'电话号码',
	DGS_ORGANIZATION_ORG_FAX:'Fax',//'传真',
	DGS_ORGANIZATION_ORG_EMAIL:'Email',//'电子邮件',
	DGS_ORGANIZATION_ORG_WEB:'Web',//'网址',
	DGS_ORGANIZATION_ORG_ADDRESS:'Address',//'地址',
	DGS_ORGANIZATION_ORG_PORFILE:'组织简介',
	DGS_ORGANIZATION_ORG_REMARK:'Remark',//'备注',
	DGS_ORGANIZATION_ORG_EXITS:'组织已存在！',
	DGS_ORGANIZATION_ORG_TIPS : '请选择组织！',
	//部门
	DGS_ORGANIZATION_DEPT_TITLE_ADD:'add dept',//'新增部门',
	DGS_ORGANIZATION_DEPT_TITLE_EDIT:'修改部门信息',
	DGS_ORGANIZATION_DEPT_TITLE_DISPLAY:'查看部门信息',
	DGS_ORGANIZATION_DEPT_NAME:'Dept Name',//'部门名称',
	DGS_ORGANIZATION_DEPT_CODE:'Dept Code',//'部门编号',
	DGS_ORGANIZATION_DEPT_PARENTID:'上级组织',
	DGS_ORGANIZATION_DEPT_ESTABLISHIMENTTIME:'成立时间',
	DGS_ORGANIZATION_DEPT_HEAD:'部门负责人',
	DGS_ORGANIZATION_DEPT_HEADPHONE:'负责人电话',
	DGS_ORGANIZATION_DEPT_CONTACT:'部门联系人',
	DGS_ORGANIZATION_DEPT_CONTACTPHONE:'联系人电话',
	DGS_ORGANIZATION_DEPT_DEPT:'部门职责',
	DGS_ORGANIZATION_DEPT_REMARK:'Remark',//'备注',
	DGS_ORGANIZATION_DEPT_EXITS:'部门已存在！',
	DGS_ORGANIZATION_DEPT_TIPS : '请选择部门！',
	/*********************组织机构管理 end*******************/
	
	/*********************用户管理 start*******************/
	DGS_USERMANAGEMENT_TIPS_ACCOUNTORNAME : 'Enter Account Or Name',//'请输入账号或姓名',
	DGS_USERMANAGEMENT_BUTTON_INIT_PASSWORD : 'Init Passward',//'初始化密码',
	DGS_USERMANAGEMENT_IS_INIT_PASSWORD : '是否确认初始化密码？',
	DGS_USERMANAGEMENT_INITPASSWORD_SUCCESS : 'Init Passward Success',//'初始化密码成功',
	DGS_USERMANAGEMENT_BUTTON_DEPART_CHANGE : '部门用户转移',
	DGS_USERMANAGEMENT_UNSELECT_DEPARMENT:'未选择部门或组织',
	DGS_USERMANAGEMENT_EXITS_DEPARMENT:'该节点下有组织部门，不能转移',
	DGS_USERMANAGEMENT_FIELD_NAME : '姓名',
	DGS_USERMANAGEMENT_TIPS_ADD : '新增用户',
	DGS_USERMANAGEMENT_TIPS_EDIT : '修改用户信息',
	DGS_USERMANAGEMENT_TIPS_DISPLAY : '查看用户信息',
	DGS_USERMANAGEMENT_ACCOUNT : '账号',
	DGS_USERMANAGEMENT_FULLNAME : '姓名',
	DGS_USERMANAGEMENT_ALIAS : '别名',
	DGS_USERMANAGEMENT_SEX : '性别',
	DGS_USERMANAGEMENT_SEX1 : '女',
	DGS_USERMANAGEMENT_SEX2 : '男',
	DGS_USERMANAGEMENT_MOBILPHONE : '手机',
	DGS_USERMANAGEMENT_PHONE : '固定电话',
	DGS_USERMANAGEMENT_EMAIL : '邮箱',
	DGS_USERMANAGEMENT_ADDRESS : '家庭地址',
	DGS_USERMANAGEMENT_LOGOUT : '允许注销',
	DGS_USERMANAGEMENT_LOGOUT1 : '是',
	DGS_USERMANAGEMENT_LOGOUT0 : '否',
	DGS_USERMANAGEMENT_STATE : '账号状态',
	DGS_USERMANAGEMENT_STATE1 : '激活',
	DGS_USERMANAGEMENT_STATE2 : '锁定',
	DGS_USERMANAGEMENT_JOBLEVEL : '岗级',
	DGS_USERMANAGEMENT_PARENTID : '所属部门',
	DGS_USERMANAGEMENT_SECURITY_CLASSIFICATION : '密级',
	DGS_USERMANAGEMENT_DEGRADE : '允许降级',
	DGS_USERMANAGEMENT_DEGRADE1 : '是',
	DGS_USERMANAGEMENT_DEGRADE0 : '否',
	DGS_USERMANAGEMENT_CHANGE : '转移至',
	DGS_USERMANAGEMENT_CHANGESUCESS : '用户转移成功!',
	DGS_USERMANAGEMENT_REMARKS : '备注',
	DGS_USERMANAGEMENT_EXITS : '账号已存在',
	DGS_USERMANAGEMENT_SUSER_UNDELETE : '系统内置用户不能删除',
	DGS_USERMANAGEMENT_SUSER_UNEDIT : '系统内置用户不能修改',
	DGS_USERMANAGEMENT_SUSER_UNINITPASSWORD : '系统内置用户不能手动初始化密码',
	DGS_USERMANAGEMENT_SELF_UNDELETE : '不能删除当前登录用户',
	DGS_USERMANAGEMENT_SELECT_ONE : '只能选择一个用户',
	DGS_USERMANAGEMENT_TEMPLATENAME : '应用模板',
	DGS_USERMANAGEMENT_SMTP : 'SMTP服务',
	DGS_USERMANAGEMENT_SMTP_PORT : '端口',
	DGS_USERMANAGEMENT_EMAIL_PASSWORD : '邮箱密码',
	/*********************用户管理 end********************/
	
	/*********************角色管理 start******************/
	DGS_ROLEMANAGEMENT_NAME : '名称',
	DGS_ROLEMANAGEMENT_TYPE : '类型',
	DGS_ROLEMANAGEMENT_DEPT : '职能',
	DGS_ROLEMANAGEMENT_REMARK : '备注',
	DGS_ROLEMANAGEMENT_AUTHS:'权限',
	DGS_ROLEMANAGEMENT_TIPS_SEARCH : '请输入角色名称',
	DGS_ROLEMANAGEMENT_TIPS_ADD : '新增角色',
	DGS_ROLEMANAGEMENT_TIPS_EDIT : '修改角色信息',
	DGS_ROLEMANAGEMENT_TIPS_DISPLAY : '查看角色信息',
	DGS_ROLEMANAGEMENT_DISTRIBUTE_USER : '分配用户',
	DGS_ROLEMANAGEMENT_DISTRIBUTE_USER_TIPS : '说明：双击左边表格中用户，或选中后点击分配按钮，可进行分配；单击右边表格中用户的删除图标，可撤销分配。',
	DGS_ROLEMANAGEMENT_USER_NAME : '姓名',
	DGS_ROLEMANAGEMENT_USER_ACCOUNT : '账号',
	DGS_ROLEMANAGEMENT_USER_SEX : '性别',
	DGS_ROLEMANAGEMENT_SUSER_UNEDIT : '系统内置角色，无法修改',
	DGS_ROLEMANAGEMENT_SUSER_UNDELETE : '系统内置角色，无法删除',
	DGS_ROLEMANAGEMENT_USER_DEPT : '所属部门',
	DGS_ROLEMANAGEMENT_IS_SELECT : '是否选中',
	DGS_ROLEMANAGEMENT_ASSIGNED_USER : '已分配用户',
	DGS_ROLEMANAGEMENT_NOT_ASSIGNED_USER : '待分配用户',
	DGS_ROLEMANAGEMENT_DEPT_TIPS : '请选择部门',
	DGS_ROLEMANAGEMENT_MAME_TIPS : '请输入账号或姓名',
	DGS_ROLEMANAGEMENT_BUTTON_DISTRIBUTE : '分配',
	DGS_ROLEMANAGEMENT_HANDLE : '操作',
	DGS_ROLEMANAGEMENT_SELECT_ONE : '只能选择一个角色',
	DGS_ROLEMANAGEMENT_EXITS : '该角色已存在！',
	/*********************角色管理 end********************/
	
	/*********************权限管理 start******************/
	DGS_AUTH_NAME:'名称',
	DGS_AUTH_CREATOR_NAME : '创建人',
	DGS_AUTH_CREATOR_TIME : '创建时间',
	DGS_AUTH_REMARK : '备注',
	DGS_AUTH_BASICINFO : '基本信息',
	DGS_AUTH_TREE_TITLE : '功能树',
	DGS_AUTH_TIPS_AUTHORIZE : '请授权！',
	DGS_AUTH_BUTTON_DISTRIBUTE_ROLE : '分配角色',
	DGS_AUTH_EXITS : '权限已存在！',
	DGS_AUTH_TIPS_NAME : '请输入权限名称',
	DGS_AUTH_DISTRIBUTE_ROLE : '分配角色',
	DGS_AUTH_DISTRIBUTE_ROLE_TIPS : '双击未分配角色，即可执行分配动作。',
	DGS_AUTH_ROLE_TREE : '角色树',
	DGS_AUTH_ROLE_NAME : '角色名称',
	DGS_AUTH_HANDLE : '操作',
	DGS_AUTH_ASSIGNED_ROLE : '已分配角色',
	DGS_AUTH_IS_SYSTEM_MODIFY : '系统内置权限，不可修改！',
	DGS_AUTH_IS_SYSTEM_DELETE : '系统内置权限，不可删除！',
	DGS_AUTH_SELECT_ONE : '只能选择一个权限',
	/*********************权限管理 end******************/
	
	/*********************终端升级 start******************/
	DGS_CLIENTPATCH_NAME:'名称',
	DGS_CLIENTPATCH_VERSION : '版本',
	DGS_CLIENTPATCH_HASH : 'md5值',
	DGS_CLIENTPATCH_SIZE : '大小',
	DGS_CLIENTPATCH_TYPE : '类型',
	DGS_CLIENTPATCH_CLIENTPATCH : '终端升级',
	DGS_CLIENTPATCH_PATCHNAMESTYLE : '升级包的格式为DGS V1.1.1.20150812.7z',
	DGS_CLIENTPATCH_PATCHNAMESTYLEERROR : '升级包格式不正确',
	DGS_CLIENTPATCH_SELECT_ONE : '只能选择一条记录',
	DGS_CLIENTPATCH_IS_MANUAL : '是否手动设置',
	DGS_CLIENTPATCH_UPGRADE_SETTING : '升级包应用',
	DGS_CLIENTPATCH_SELECT_ALL : '全选',
	DGS_CLIENTPATCH_APPLY_CHILD : '应用到子项',
	DGS_CLIENTPATCH_SEARCH_TIP : '请输入名称',
	DGS_CLIENTPATCH_SEARCH_ALL : '查询全部',
	DGS_CLIENTPATCH_NOT_SETTING : '升级包导入时未设置手动配置！',
	/*********************终端升级 end******************/
	
	/*********************系统操作日志 start******************/
	DGS_OPERATOR_LOG_NAME : '操作人',
	DGS_OPERATOR_LOG_IP : '操作IP',
	DGS_OPERATOR_LOG_MODULE_NAME : '操作模块',
	DGS_OPERATOR_LOG_TIME : '操作时间',
	DGS_OPERATOR_LOG_CONTENT : '操作内容',
	DGS_OPERATOR_LOG_START_TIME : '操作时间起',
	DGS_OPERATOR_LOG_END_TIME : '操作时间止',
	DGS_OPERATOR_LOG_STATE : '状态',
	DGS_OPERATOR_LOG_SUCCESS : '成功',
	DGS_OPERATOR_LOG_FAILURE : '失败',
	DGS_OPERATOR_LOG_DATE_ERROR : '起始日期不能大于截止日期！',
	/*********************系统操作日志 end******************/
	
	/*********************文档库操作日志 start******************/
	DGS_DOCUMENT_OPERATOR_LOG_NAME : '操作人',
	DGS_DOCUMENT_OPERATOR_LOG_IP : '操作IP',
	DGS_DOCUMENT_OPERATOR_LOG_MODULE_NAME : '操作模块',
	DGS_DOCUMENT_OPERATOR_LOG_TIME : '操作时间',
	DGS_DOCUMENT_OPERATOR_LOG_CONTENT : '操作内容',
	DGS_DOCUMENT_OPERATOR_LOG_FILEPATH : '文件路径',
	DGS_DOCUMENT_OPERATOR_LOG_REMARK : 'Remark',//'备注',
	DGS_DOCUMENT_OPERATOR_LOG_START_TIME : 'Start Time',//'操作时间起',
	DGS_DOCUMENT_OPERATOR_LOG_END_TIME : 'End Time',//'操作时间止',
	DGS_DOCUMENT_OPERATOR_LOG_STATE : 'State',//'状态',
	DGS_DOCUMENT_OPERATOR_LOG_SELECT_ONE : '只能选择一条日志',
	DGS_DOCUMENT_OPERATOR_LOG_TIPS_DISPLAY:'查看',
	DGS_DOCUMENT_OPERATOR_LOG_DATE_ERROR : '起始日期不能大于截止日期！',
	/*********************系统操作日志 end******************/
	
	/*********************DM模块名称 start******************/
	DM_TAB_DOC : 'Doc',//'文档',
	DM_TAB_SEARCH : 'Search',//'搜索',
	DM_MENU_CLASSIC_DOC : '分类文件库',
	DM_MENU_TOP_LABEL : '热门标签',
	DM_MENU_MY_DOC : '我的文档',
	DM_MENU_PERSONAL_FAVORITES : '个人收藏夹',
	DM_MENU_WORK_DOCUMENT : '工作文档',
	DM_MENU_RECYCLE : '回收站',
	DM_MENU_FILE_RECORD : '审批记录',
	DM_MENU_APPLICATION_RECORD : '申请记录',
	DM_MENU_CAPTURER_EGISTER : '捕获登记',
	/*********************DM模块名称 end******************/
	
	/*********************文件文件夹管理 start******************/
	DM_DOC_FOLDER_LENGTH_ERROR : '文件夹长度达到上限，无法创建！',
	DM_DOC_FOLDER_OUT_OF_LEVEL : '当前层级文件夹个数达到上限，无法创建！',
	DM_DOC_BUTTON_CREATE_FOLDER : '新增文件夹',
	DM_DOC_BUTTON_ADD_RECORD : '新增记录',
	DM_DOC_BUTTON_UPLOAD : '上传文档',
	DM_DOC_BUTTON_MOVE : '移动',
	DM_DOC_BUTTON_DOWNLOAD : '下载',
	DM_DOC_BUTTON_APPLY_FILING : '申请归档',
	DM_DOC_BUTTON_FAVORITE : '收藏',
	DM_DOC_BUTTON_SAFE_CONTROL : '安全控制',
	DM_DOC_BUTTON_UPDATE_VERSION : '版本更新',
	DM_DOC_BUTTON_PREVIEW : '预览',
	DM_DOC_BUTTON_COMMENT : '评论',
	DM_DOC_BUTTON_HOT_TAG : '标签',
	DM_DOC_TIPS_NAME : '请输入名称',
	DM_DOC_NOT_SELECT_ROOT : '不能选择根目录！',
	DM_DOC_SELECT_NODE : '请选择左侧目录！',
	DM_DOC_NOT_DOWNLOAD_FOLDER : '文件夹无法下载！',
	DM_DOC_TEXT_NAME : '名称',
	DM_DOC_TEXT_TYPE : '类型',
	DM_DOC_TEXT_SIZE : '大小',
	DM_DOC_TEXT_STATUS : '归档状态',
	DM_DOC_TEXT_SECURITY : '密级',
	DM_DOC_TEXT_VERSION : '版本号',
	DM_DOC_TEXT_PATH : '路径',
	DM_DOC_TEXT_MODIFY_TIME : '更新日期',
	DM_DOC_TEXT_DUE_TIME : '到期时间',
	DM_DOC_TEXT_TRANSFORM_STATE : '转换状态',
	DM_DOC_TEXT_FOLDER_STATE : '文件夹使用状态',
	DM_DOC_TEXT_CREATE_TIME : '创建时间',
	DM_DOC_FOLDER_EXITS : '文件夹已存在！',
	DM_DOC_CREATE_FOLDER : '新增文件夹',
	DM_DOC_EDIT_FOLDER : '修改文件夹',
	DM_DOC_FOLDER_NAME : '文件夹名称',
	DM_DOC_PARENT_NODE : '上层节点',
	DM_DOC_IMAGE : '文件夹类型',
	DM_DOC_REMARK : '备注',
	DM_DOC_EDIT : '修改文件',
	DM_DOC_BASE_INFO : '基本信息',
	DM_DOC_NAME : '文件名称',
	DM_DOC_NAME_SPECIAL_CHARACTER : '不能包含下列任何字符之一：?、\/*“”<>|',
	DM_DOC_DELETE　: '将删除子文件夹和文件，是否确认删除？',
	DM_DOC_MOVE_ERROR　: '无法移动到子文件夹下',
	DM_DOC_MOVE_EXIST_ERROR : '目标文件夹下重名',
	DM_DOC_NO_FILE : '不存在实体文件，无法下载！',
	DM_DOC_DOCUMENT_STATE : '文档状态',
	DM_DOC_DOCUMENT_STATE1 : '未归档',
	DM_DOC_DOCUMENT_STATE2 : '已归档',
	DM_DOC_DOCUMENT_STATE3 : '审批中',
	DM_DOC_DOCUMENT_STATE5 : '已驳回',
	DM_DOC_CLASSIC_DOCUMENT : '分类文件库',
	DM_DOC_WORK_DOCUMENT : '工作文档',
	DM_DOC_MOVE_REASON : '原因',
	DM_DOC_SELECT_ONE : '只能选择一个文件（夹）',
	DM_DOC_SELECT_ONE_DOC : '只能选择一个文件',
	DM_DOC_SELECT_ONE_FOLDER : '只能选择一个文件夹',
	DM_DOC_MOVE_ROOT_ERROR : '文件无法移动到根目录',
	DM_DOC_FOLDER_SELECTE_ERROR : '不能选择文件夹',
	DM_DOC_SELECTE_ERROR : '不能选择文件！',
	DM_DOC_FILING_ERROR : '只能选择未归档或已驳回文件（夹）',
	DM_DOC_NOT_DELETE_FILING : '审批中的文件（夹）不可以删除！',
	DM_DOC_UNFILING : '未归档',
	DM_DOC_FILING : '待归档',
	DM_DOC_FILED : '已归档',
	DM_DOC_SELECT_DOCUMENT : '请选择文档！',
	DM_DOC_SELECT_NOT_FILED_DOC : '只能选择未归档或已驳回文档进行版本更新！',
	DM_DOC_URDATE_VERSION : '版本更新',
	DM_DOC_CURRENT_DOC : '当前文件',
	DM_DOC_SELECT_DOC : '选择文件',
	DM_DOC_BROWSE : '浏览...',
	DM_DOC_WAIT_UPLOAD : '正在上传...',
	DM_DOC_UPLOAD_SUCCESS : '上传成功！',
	DM_DOC_SELECT_SAME_DOC : '说明：选择相同名称的文件。',
	DM_DOC_DELETE_NO_FILED_DOC : '只能删除未归档的文档，请重新选择！',
	DM_DOC_NOT_FAVORITE_FOLDER : '文件夹无法收藏！',
	DM_DOC_AUTH_AUTHORIZE : '没有授权权限！',
	DM_DOC_AUTH_CREATE_FOLDER : '没有新建文件夹权限！',
	DM_DOC_AUTH_EDIT : '没有修改权限！',
	DM_DOC_AUTH_DELETE : '没有删除权限！',
	DM_DOC_AUTH_CREATE_DOCUMENT : '没有上传文档权限！',
	DM_DOC_AUTH_ADD_RECORD : '没有新增记录权限！',
	DM_DOC_AUTH_VERSION_UPDATE : '没有版本更新权限！',
	DM_DOC_AUTH_PERVIEW : '没有预览权限！',
	DM_DOC_AUTH_DOWNLOAD : '没有下载权限！',
	DM_DOC_AUTH_RENEW : '没有续存权限！',
	DM_DOC_SELECT_VERSION_DOWNLOAD : '请选择一个版本进行下载！',
	/*********************文件文件夹管理 end******************/
	
	/*********************上传文档 start******************/
	DM_UPLOAD_SELECT : '选择文件',
	DM_UPLOAD_SELECT_DOC : '上传',
	DM_UPLOAD_REMOVE : '移除所有',
	DM_UPLOAD_CANCEL : '取消上传',
	DM_UPLOAD_DOC : '上传文档',
	DM_UPLOAD_DOC_NAME : '文件名',
	DM_UPLOAD_TYPE : '类型',
	DM_UPLOAD_SIZE : '大小',
	DM_UPLOAD_SECURITY : '密级',
	DM_UPLOAD_PERCENT : '进度',
	DM_UPLOAD_STATUS : '状态',
	DM_UPLOAD_STATUS_WAIT : '等待上传',
	DM_UPLOAD_STATUS_UPLOADING : '上传中...',
	DM_UPLOAD_STATUS_FAILURE : '上传失败',
	DM_UPLOAD_STATUS_SUCCESS : '上传成功',
	DM_UPLOAD_STATUS_STOP : '停止上传',
	DM_UPLOAD_DELETE : '移除',
	DM_UPLOAD_VERSION_LOW : '浏览器Flash Player版本太低,不能使用该上传功能！',
	DM_UPLOAD_QUEUE_LIMIT_EXCEEDED : '上传文件列表数量超限,不能选择！',
	DM_UPLOAD_FILE_EXCEEDS_SIZE_LIMIT : '文件大小超过限制, 不能选择！',
	DM_UPLOAD_ZERO_BYTE_FILE : '该文件大小为0,不能选择！',
	DM_UPLOAD_INVALID_FILETYPE : '该文件类型不允许上传！',
	DM_UPLOAD_SWF_FAILURE : 'SWFUpload加载失败！',
	DM_UPLOAD_TIPS : '重名的文档会进行自动重名纠正，如"test"文档，上传后更正为"test(1)"。',
	/*********************上传文档 end******************/
	
	/*********************安全控制 start******************/
	DM_SAFE_CONTROL_TITLE : '安全控制',
	DM_SAFE_CONTROL_SEARCH_NAME : '请输入名称',
	DM_SAFE_CONTROL_TEXT_NAME : '名称',
	DM_SAFE_CONTROL_TEXT_SELECT : '是否已分配',
	DM_SAFE_CONTROL_USER_GROUP : '用户组列表',
	DM_SAFE_CONTROL_ACL : 'ACL控制权限详情',
	DM_SAFE_CONTROL_FOLDER_ACL : '文件夹权限',
	DM_SAFE_CONTROL_CLEAR_ALL : '清空',
	DM_SAFE_CONTROL_SELECT_ALL : '全选',
	DM_SAFE_CONTROL_REVERSE_SELECT : '反选',
	DM_SAFE_CONTROL_APPLY_CHILD : '应用到子项',
	DM_SAFE_CONTROL_FOLDER_AUTHORIZE : '授权',
	DM_SAFE_CONTROL_CREATE_FOLDER : '创建',
	DM_SAFE_CONTROL_EDIT_FOLDER : '修改',
	DM_SAFE_CONTROL_RENAME_FOLDER : '重命名',
	DM_SAFE_CONTROL_DELETE_FOLDER : '删除',
	DM_SAFE_CONTROL_AUTO_ARCHIVE : '自动归档',
	DM_SAFE_CONTROL_DOC_ACL : '文件权限',
	DM_SAFE_CONTROL_DOCUMENT_AUTHORIZE : '授权',
	DM_SAFE_CONTROL_CREATE_DOCUMENT : '创建',
	DM_SAFE_CONTROL_EDIT_DOCUMENT : '修改',
	DM_SAFE_CONTROL_RENAME_DOCUMENT : '重命名',
	DM_SAFE_CONTROL_DELETE_DOCUMENT : '删除',
	DM_SAFE_CONTROL_VERSION_UPDATE : '版本更新',
	DM_SAFE_CONTROL_PERVIEW : '预览',
	DM_SAFE_CONTROL_DOWNLOAD : '下载',
	DM_SAFE_CONTROL_RENEW : '续存',
	DM_SAFE_CONTROL_SELECT_GROUP : '请选择用户组！',
	/*********************安全控制 end******************/
	
	/*********************个人收藏夹 start******************/
	DM_FAVORITES_TITLE : '个人收藏夹',
	DM_FAVORITES_TITLE_MOVE_TO : '移动到',
	DM_FAVORITES_TITLE_ADD_TO : '添加到收藏夹',
	DM_FAVORITES_TEXT_NAME : '名称',
	DM_FAVORITES_TEXT_PATH : '路径',
	DM_FAVORITES_TEXT_DATE : '日期',
	DM_FAVORITES_SELECT : '请选择收藏夹！',
	/*********************个人收藏夹 end******************/
	
	/*********************用户组管理 start******************/
	DGS_USERGROUP_DISTRIBUTE_USER : '分配用户',
	DGS_USERGROUP_TIPS_NAME : '请输入用户组名称',
	DGS_USERGROUP_TIPS_ADD : '新增用户组',
	DGS_USERGROUP_TIPS_EDIT : '修改用户组',
	DGS_USERGROUP_TIPS_DISPLAY : '查看用户组',
	DGS_USERGROUP_EXITS : '用户组已存在',
	DGS_USERGROUP_NAME : '用户组名称',
	DGS_USERGROUP_REMARK : '备注',
	DGS_USERGROUP_SELECT_ONE : '只能选择一个用户组',
	DGS_USERGROUP_DISTRIBUTE_USER_TIPS : '说明：双击左边表格中用户，或选中后点击分配按钮，可进行分配；单击右边表格中用户的删除图标，可撤销分配。',
	DGS_USERGROUP_DEPT_TIPS : '请选择部门',
	DGS_USERGROUP_DEPT_SELECT : '请选择组织或部门',
	DGS_USERGROUP_MAME_TIPS : '请输入账号或姓名',
	DGS_USERGROUP_BUTTON_DISTRIBUTE : '分配',
	DGS_USERGROUP_USER_ACCOUNT : '账号',
	DGS_USERGROUP_USER_NAME : '姓名',
	DGS_USERGROUP_USER_DEPT : '所属部门',
	DGS_USERGROUP_IS_SELECT : '是否选中',
	DGS_USERGROUP_HANDLE : '操作',
	DGS_USERGROUP_REMARK : '备注',
	DGS_USERGROUP_GROUPINGUSER_SELECT_ALL : '查询全部',
	/*********************用户组管理 end******************/
	
	/*********************审批记录 start******************/
	DM_CATCHREGISTER_BUTTON_REGISTER : '审批',
	DM_CATCHREGISTER_BUTTON_ENTRUST : '委托',
	DM_CATCHREGISTER_BUTTON_CANCEL_ENTRUST : '取消委托',
	DM_CATCHREGISTER_APPLY_FILING : '归档申请',
	DM_CATCHREGISTER_START_TIME :　'申请开始日期',
	DM_CATCHREGISTER_END_TIME : '申请截止日期',
	DM_CATCHREGISTER_UNDER_REGISTER : '待审批',
	DM_CATCHREGISTER_AGREE : '已归档',
	DM_CATCHREGISTER_DISAGREE : '已驳回',
	DM_CATCHREGISTER_STATE : '状态',
	DM_CATCHREGISTER_APPLY_TIME : '申请时间',
	DM_CATCHREGISTER_APPLY_USERNAME :　'申请人',
	DM_CATCHREGISTER_AUDITOR_USERNAME : '审批人',
	DM_CATCHREGISTER_APPLY_REASON :　'归档说明',
	DM_CATCHREGISTER_ALREADY_REGISER_ERROR : '请选择待审批的记录！',
	DM_CATCHREGISTER_TITLE_REGISTER : '审批',
	DM_CATCHREGISTER_APPLY_INFO : '申请信息',
	DM_CATCHREGISTER_META_DATA : '元数据信息',
	DM_CATCHREGISTER_DOC_LIST　: '申请列表',
	DM_CATCHREGISTER_APPROVAL_INFO : '审计信息',
	DM_CATCHREGISTER_FILING_PATH : '归档路径',
	DM_CATCHREGISTER_FILING_REASON : '审批说明',
	DM_CATCHREGISTER_DOC_NAME : '名称',
	DM_CATCHREGISTER_DOC_VERSION : '版本号',
	DM_CATCHREGISTER_DOC_SECURITY : '密级',
	DM_CATCHREGISTER_DOC_OPRATION : '操作',
	DM_CATCHREGISTER_FILE_SELECTION_ERROR : '未选择文件',
	DM_CATCHREGISTER_FILED_TIME : '审批时间',
	DM_CATCHREGISTER_DATE_ERROR : '开始日期不能大于截止日期！',
	DM_CATCHREGISTER_APPROVAL_INFO : '审批记录',
	DM_CATCHREGISTER_APPROVER_NAME : '审批人',
	DM_CATCHREGISTER_APPROVER_TIME : '审批时间',
	DM_CATCHREGISTER_APPROVER_REMARK : '审批原因',
	DM_CATCHREGISTER_NODE_GRADE : '节点等级',
	DM_CATCHREGISTER_APPROVER_STATUS : '审批状态',
	DM_CATCHREGISTER_APPROVER_STATUS1 : '待审批',
	DM_CATCHREGISTER_APPROVER_STATUS2 : '审批通过',
	DM_CATCHREGISTER_APPROVER_STATUS3 : '审批驳回',
	DM_CATCHREGISTER_APPROVER_STATUS4 : '已委托',
	DM_CATCHREGISTER_BUTTON_AGREE : '同意',
	DM_CATCHREGISTER_BUTTON_DISAGREE : '驳回',
	DM_CATCHREGISTER_WORKFLOW_ERROR : '审批流程有误，异常结束！',
	DM_CATCHREGISTER_BUTTON_NO_APPROVER : '没有合适的审批人',
	DM_CATCHREGISTER_SELECT_APPROVER : '选择审批人',
	DM_CATCHREGISTER_NEXT_APPROVER : '下一审批人',
	DM_CATCHREGISTER_SELECT_ENTRUST : '选择委托人',
	DM_CATCHREGISTER_ENTRUST : '受委托人',
	DM_CATCHREGISTER_IS_CANCEL_ENTRUST : '是否确认取消委托？',
	/*********************审批记录 end******************/
	

	/*********************授权管理 start******************/
	DGS_ACCREDITATION_BUTTON_UPLOADCONTROL :　'导入授权',
	DGS_ACCREDITATION_BUTTON_ACCDISTRIBUTE : '授权设置',
	DGS_ACCREDITATION_SELECT_USER :'至少选择一个部门或者一个用户',
	DGS_ACCREDITATION_SELECT_PRODUCT :'至少选择一个产品',
	DGS_ACCREDITATION_NO_LIC :'没有安装license文件,请先导入授权',
	DGS_ACCREDITATION_OUT_OF_USER :'超出授权人数,请重新选择',
	DGS_ACCREDITATION_ACCRED_USER_NUM :'授权用户数',
	DGS_ACCREDITATION_HAS_ACCRED_USER_NUM :'已授权用户数',
	DGS_ACCREDITATION_ONLINE_USER_NUM :'在线用户数',
	DGS_ACCREDITATION_ACCRED_MACHINE_NUM :'授权设备数',
	DGS_ACCREDITATION_HAS_ACCRED_MACHINE_NUM :'已授权设备数',
	DGS_ACCREDITATION_ONLINE_MACHINE_NUM :'在线设备数',
	DGS_ACCREDITATION_UNIT_NUM :'企业码',
	DGS_ACCREDITATION_UNIT_NAME :'企业名',
	DGS_ACCREDITATION_UNIT_ADDR :'地址',
	DGS_ACCREDITATION_UNIT_USER :'联系人',
	DGS_ACCREDITATION_UNIT_USER_PHONE :'联系人电话',
	DGS_ACCREDITATION_START_TIME :'试用开始时间',
	DGS_ACCREDITATION_IS_UNOFFICIAL_NUM :'是否试用号',
	DGS_ACCREDITATION_IS_TRYOUT_DAY :'试用天数',
	DGS_ACCREDITATION_REMAINDER_DAY :'剩余天数',
	DGS_ACCREDITATION_BUTTON_CANCEL :'取消授权',
	DGS_ACCREDITATION_BUTTON_SAVE :'授权',
	DGS_ACCREDITATION_SELECT_PRODUCT :'选择产品',
	DGS_ACCREDITATION_DEPT :'组织机构',
	DGS_ACCREDITATION_ACCOUNT :'账号',
	DGS_ACCREDITATION_USERNAME :'姓名',
	DGS_ACCREDITATION_DM_ACCRED :'DM授权',
	DGS_ACCREDITATION_ACCRED_SUCCESS :'授权成功',
	DGS_ACCREDITATION_UNACCRED_SUCCESS :'取消授权成功',
	DGS_ACCREDITATION_UPLOAD_FILE :'上传授权文件',
	DGS_ACCREDITATION_FILE_TYPE :'文件类型为lic',
	DGS_ACCREDITATION_IS_SAVE : '是否保存已授权的模块（不保存将被重置）？',
	DGS_ACCREDITATION_OUT_OF_MAX : '授权数超过上限',
	DGS_ACCREDITATION_YES : '是',
	DGS_ACCREDITATION_NO : '否',
	DGS_ACCREDITATION_TAB_DM : 'DM授权',
	DGS_ACCREDITATION_TAB_DG : 'DG授权',
	DGS_ACCREDITATION_UPLOAD_SUCCESS_TIP :'上传成功！<br/>如果当前是集群部署，请重启所有的tomcat服务，重新登录方能生效！<br/>如果当前不是集群部署，则需要重新登录方能生效！',
	/*********************授权管理 end********************/
	
	/*********************系统配置 start******************/
	DGS_SYSTEMSET_BUTTON_SAVE : '保存',
	DGS_SYSTEMSET_UPLOAD_PATH : '文档库存储路径',
	DGS_SYSTEMSET_FD_PATH : '文档安全存储路径',
	DGS_SYSTEMSET_BASE_PATH : '基础存储路径',
	DGS_SYSTEMSET_PREVIEW_PATH : '预览存储路径',
	DGS_SYSTEMSET_ACL_POOL_SIZE : 'ACL线程池大小',
	DGS_SYSTEMSET_TIKA_POOL_SIZE : 'tika线程池大小',
	DGS_SYSTEMSET_PREVIEW_POOL_SIZE : '预览线程池大小',
	DGS_SYSTEMSET_SOLR_PATH : 'solr地址',
	DGS_SYSTEMSET_BASE_REMARK : '(用于存放升级包)',
	DGS_SYSTEMSET_UPLOAD_REMARK : '(用于存放上传的文件)',
	DGS_SYSTEMSET_PREVIEW_REMARK : '(用于存放预览时转换的临时文件)',
	DGS_SYSTEMSET_FD_REMARK : '(用于存放外发文件)',
	DGS_SYSTEMSET_SOLR_REMARK : '(用于存放搜索所需的索引文件)',
	DGS_SYSTEMSET_SAVE_SUCCESS_TIP : '操作成功！<br/>如果当前是集群部署，则需要重启服务器方能生效！',
	DGS_SYSTEMSET_EMAIL_SMTP : 'SMTP服务',
	DGS_SYSTEMSET_EMAIL_SMTP_PORT : '端口',
	DGS_SYSTEMSET_EMAIL_SMTP_REMARK : '(配置系统发件邮箱的服务器)',
	DGS_SYSTEMSET_EMAIL : '邮箱账号',
	DGS_SYSTEMSET_EMAIL_PASSWORD : '密码',
	DGS_SYSTEMSET_EMAIL_REMARK : '(配置系统发件邮箱)',
	/*********************系统配置 end********************/
	
	/*********************AD管理 start******************/
	DGS_AD_BUTTON_SYNC :　'同步',
	DGS_AD_TIPS : '请输入名称',
	DGS_AD_TEXT_NAME : '名称',
	DGS_AD_TEXT_TYPE : '类型',
	DGS_AD_TEXT_IP : 'IP地址',
	DGS_AD_TEXT_PORT : '端口',
	DGS_AD_TEXT_DOMAIN : '域名',
	DGS_AD_TEXT_BASE_DN : '同步节点',
	DGS_AD_TEXT_REMARK : '备注',
	DGS_AD_TEXT_CREATOR_TIME : '创建时间',
	DGS_AD_TEXT_STATUS : '状态',
	DGS_AD_TEXT_STATUS1 : '未同步',
	DGS_AD_TEXT_STATUS2 : '已同步',
	DGS_AD_TIPS_SYNC : '确认同步？',
	DGS_AD_NO_CONNECTION : '连接出错，无法同步！',
	DGS_AD_LOGIN_ERROR : '账号或凭据错误，无法同步！',
	DGS_AD_NO_EXISTS : '基础DN不存在，无需同步！',
	DGS_AD_EXIST : '已同步，无需同步！',
	DGS_AD_FIELD_NAME : '名称',
	DGS_AD_FIELD_TYPE : '类型',
	DGS_AD_FIELD_IP : 'IP地址',
	DGS_AD_TIPS_IP : 'IP不正确！',
	DGS_AD_FIELD_PORT : '端口',
	DGS_AD_TIPS_PORT : '端口数在1~65535之间！',
	DGS_AD_FIELD_DOMAIN : '域名',
	DGS_AD_FIELD_BASE_DN : '同步节点',
	DGS_AD_FIELD_ACCOUNT : '管理员账号',
	DGS_AD_FIELD_PASSWORD : '管理员凭据',
	DGS_AD_FIELD_REMARK : '备注',
	DGS_AD_EXIST : '该名称已存在！',
	DGS_AD_TIPS_SYNC : '正在同步，请稍候...',
	DGS_AD_TITLE_SYNC : '同步',
	DGS_AD_SYNC_ORGA : '组织',
	DGS_AD_SYNC_ORGA_USER : '组织+用户',
	DGS_AD_SYNC_ORGA_TERMINAL : '组织+终端信息',
	DGS_AD_SYNC_ALL : '全部',
	/*********************AD管理 end********************/
	
	/*********************评论 start******************/
	DM_COMMENT_TITLE : '评论',
	DM_COMMENT_TEXT_CREATOR : '评论人',
	DM_COMMENT_TEXT_START_TIME : '评论时间起',
	DM_COMMENT_TEXT_END_TIME : '评论时间止',
	DM_COMMENT_TEXT_DOC_NAME : '文档',
	DM_COMMENT_TEXT_CONTENT : '评论内容',
	DM_COMMENT_TEXT_CREATE_TIME : '评论时间',
	DM_COMMENT_TEXT_DOC : '评论的文档',
	DM_COMMENT_TEXT_GRADE : '评分',
	DM_COMMENT_TEXT_COMMENT : '评论',
	DM_COMMENT_SELECT_ONE : '只能选择一个评论！',
	DM_COMMENT_EXCUTE_RATE : '评分...',
	DM_COMMENT_RATE_BAD : '较差',
	DM_COMMENT_RATE_NOTBAD : '还可以',
	DM_COMMENT_RATE_OK : '好',
	DM_COMMENT_RATE_BETTER : '相当好',
	DM_COMMENT_RATE_PERFECT : '好极了',
	DM_COMMENT_RATE_RESULT : '评分结果！',
	DM_COMMENT_GRADE_UNIT : '分',
	DM_COMMENT_DATE_ERROR : '起始日期不能大于截止日期！',
	/*********************评论 end******************/
	
	/*********************文件文件夹类型管理 start******************/
	DM_TYPE_IMG : '图标',
	DM_TYPE_FOLDER_NAME : '文件夹类型名称',
	DM_TYPE_MODIFY_TIME : '更新时间',
	DM_TYPE_REMARK : '备注',
	DM_TYPE_SELECT_ONE_DOC : '只能选择一个文件类型！',
	DM_TYPE_SELECT_ONE_FOLDER : '只能选择一个文件夹类型！',
	DM_TYPE_NAME : '名称',
	DM_TYPE_SMALL_IMG : '小图标',
	DM_TYPE_BIG_IMG : '大图标',
	DM_TYPE_EXIST_NAME : '类型名称重复！',
	/*********************文件文件夹类型管理 end******************/
	
	/*********************标签管理 start******************/
	DM_TAG_NOT_EXIST : '暂无标签',
	DM_TAG_NAME : '标签名称',
	DM_TAG_DOC_NAME : '文档名称',
	DM_TAG_CREATOR_NAME : '创建人名称',
	DM_TAG_START_TIME : '创建时间起',
	DM_TAG_END_TIME : '创建时间止',
	DM_TAG_CREATOR : '创建人',
	DM_TAG_CREATOR_TIME : '创建时间',
	DM_TAG_TITLE : '标签',
	DM_TAG_LIST : '标签列表',
	DM_TAG_NEW : '新建标签',
	DM_TAG_ADD : '添加',
	DM_TAG_TIPS : '说明：点击标签，标签底色显示红色为待删除标签，再次点击还原，点击保存后操作成功。',
	DM_TAG_TIP_NOT_NULL : '标签内容不能为空！',
	DM_TAG_TIP_TOO_LONG : '标签内容太长！',
	DM_TAG_TIP_EXIST : '标签已存在！',
	DM_TAG_TIP_MORE : '标签不能超过20个！',
	DM_TAG_DATE_ERROR : '起始日期不能大于截止日期！',
	/*********************标签管理 end******************/
	
	/*********************回收站 start******************/
	DM_RECYCLE_RECOVERY : '恢复',
	DM_RECYCLE_EXIST : '目标文件夹中已存在该名称文件，请重新选择！',
	DM_RECYCLE_RECOVERY_TO : '还原到',
	DM_RECYCLE_RECOVERY_TO_FOLDER : '请选择还原到的文件夹',
	/*********************回收站 end******************/
	
	/*********************预览 start******************/
	DM_PREVIEW_TITLE : '文档在线查看',
	DM_PREVIEW_DOC_PROPERTY : '文档属性',
	DM_PREVIEW_HISTORY_VERSION : '历史版本',
	DM_PREVIEW_RELATED_COMMENTS : '相关评论',
	DM_PREVIEW_TIPS_TYPE : '不支持该格式的文档预览！',
	DM_PREVIEW_TIPS_TRANSFORM : '文件未转换成功！',
	/*********************预览 end******************/
	
	/*********************搜索 start******************/
	DM_SEARCH_ADVANCED_TERMS : '高级搜索条件',
	DM_SEARCH_FILE_TYPE : '文档类型：',
	DM_SEARCH_FILE_TYPE_ALL : '全部',
	DM_SEARCH_TYPE : '搜索类型：',
	DM_SEARCH_TYPE_CONTENT_PROPERTY : '内容+属性',
	DM_SEARCH_TYPE_CONTENT : '内容',
	DM_SEARCH_TYPE_PROPERTY : '属性',
	DM_SEARCH_CREATOR : '文档创建人：',
	DM_SEARCH_FILING_TIME : '归档时间：',
	DM_SEARCH_FILING_TIME_TO : '至',
	DM_SEARCH_FILING_TIME_TIP : '提示：时间格式为"2015-04-03"',
	DM_SEARCH_MY_CONDITION : '自定义查询属性',
	DM_SEARCH_HOT_TAG : '热门标签',
	DM_SEARCH_TAG_FILTERING : '标签过滤',
	DM_SEARCH_KEYWORD : '请输入搜索关键词！',
	DM_SEARCH_TAG : '标签：',
	DM_SEARCH_QTIME : '搜索耗时',
	DM_SEARCH_QTIME_UNIT : '毫秒,共',
	DM_SEARCH_TOTAL : '个结果。',
	DM_SEARCH_PREVIEW : '预览全文',
	DM_SEARCH_DOWNLOAD : '下载',
	DM_SEARCH_FAVORITE : '收藏',
	DM_SEARCH_UNKNOWN_PAGE : '未知页数',
	DM_SEARCH_TOTAL_PAGE : '共',
	DM_SEARCH_PAGE_UNIT : '页',
	DM_SEARCH_NO_CREATOR : '匿名贡献者',
	DM_SEARCH_DOC_CREATOR : '贡献者：',
	DM_SEARCH_UPDATE_TIME : '更新时间：',
	DM_SEARCH_DOC_VERSION : '版本号：',
	/*********************搜索 end******************/
	
	/*********************终端设备管理 start******************/
	DGS_TERMINAL_MOVE : '移动',
	DGS_TERMINAL_SEARCH_TIP : '请输入终端名称或资产责任者',
	DGS_TERMINAL_TEXT_NAME : '终端名称',
	DGS_TERMINAL_TEXT_TYPE : '终端类型',
	DGS_TERMINAL_TEXT_SYSTEM : '操作系统类型',
	DGS_TERMINAL_TEXT_DEVICE_TYPE : '设备型号',
	DGS_TERMINAL_TEXT_IP : 'IP',
	DGS_TERMINAL_TEXT_LOGIN_TIME : '最后登录时间',
	DGS_TERMINAL_TEXT_DEPARTMENT : '所属部门',
	DGS_TERMINAL_TEXT_MANAGER : '资产责任者',
	DGS_TERMINAL_TEXT_REMARK : '备注',
	DGS_TERMINAL_SELECT_ONE : '只能选择一个终端设备',
	DGS_TERMINAL_MOVE_TO : '移动到',
	DGS_TERMINAL_EXITS : '该终端已存在！',
	/*********************终端设备管理 end******************/
	
	/*********************应用软件管理 start******************/
	DGS_SOFTWARE_ROOT : '软件分类',
	DGS_SOFTWARE_ADD_CLASS : '新增软件分类',
	DGS_SOFTWARE_ADD : '新增软件',
	DGS_SOFTWARE_COPY : '复制',
	DGS_SOFTWARE_MODIFY : '修改',
	DGS_SOFTWARE_DELETE : '删除',
	DGS_SOFTWARE_EXPORT : '导出',
	DGS_SOFTWARE_EXPORT_DATA : '导出数据',
	DGS_SOFTWARE_EXPORT_SQL : '导出脚本',
	DGS_SOFTWARE_ADD_PROCESS : '新增进程',
	DGS_SOFTWARE_MODIFY_PROCESS : '修改进程',
	DGS_SOFTWARE_DELETE_PROCESS : '删除进程',
	DGS_SOFTWARE_VIEW_PROCESS : '查看进程',
	DGS_SOFTWARE_SEARCH_TIP : '请输入进程名称',
	DGS_SOFTWARE_TEXT_PROCESS_NAME : '进程名称',
	DGS_SOFTWARE_TEXT_KERNEL_PROCESS : '核心进程',
	DGS_SOFTWARE_TEXT_CONTROL_PROCESS : '控制台进程',
	DGS_SOFTWARE_TEXT_SERVICE_PROCESS : '服务进程',
	DGS_SOFTWARE_TEXT_ENCRY_EXTENSION : '加密扩展名',
	DGS_SOFTWARE_TEXT_MONITOR_EXTENSION : '监控扩展名',
	DGS_SOFTWARE_TEXT_EXTENSION_TIP : '以;作为分隔符、开始、结尾，扩展名以.开始，示例：;.TMP;.DOC;',
	DGS_SOFTWARE_TEXT_SPECIAL_DOC : '特殊文件名',
	DGS_SOFTWARE_TEXT_SPECIAL_DOC_TIP : '以;作为分隔符、开始、结尾，示例：;NORMAL.DOTM;~$OXMAIL;',
	DGS_SOFTWARE_TEXT_SPECIAL_PATH : '特殊路径',
	DGS_SOFTWARE_TEXT_PE_PATH : 'PE路径',
	DGS_SOFTWARE_TIP_SELECT_ONE_CLASS : '请选择一个软件分类！',
	DGS_SOFTWARE_TIP_SELECT_NOT_ROOT : '不可以选择根节点！',
	DGS_SOFTWARE_TIP_SELECT_ONE : '请选择一个软件（分类）！',
	DGS_SOFTWARE_TIP_NOT_MODIFY_ROOT : '不可以修改根节点！',
	DGS_SOFTWARE_TIP_NOT_MODIFY_SYSTEM : '内置的软件（分类）不可修改！',
	DGS_SOFTWARE_TIP_NOT_DELETE_SYSTEM : '内置的软件（分类）不可删除！',
	DGS_SOFTWARE_TIP_NOT_COPY_ROOT : '不可以复制根节点！',
	DGS_SOFTWARE_TIP_SELECT_ONE_SOFTWARE : '请选择一个软件！',
	DGS_SOFTWARE_TIP_SELECT_ONE_PROCESS : '请选择一个进程！',
	DGS_SOFTWARE_TIP_NOT_MODIFY_SYSTEM_PROCESS : '内置的进程不可修改！',
	DGS_SOFTWARE_TIP_NOT_DELETE_SYSTEM_PROCESS : '内置的进程不可删除！',
	DGS_SOFTWARE_TIP_EXIST : '该名称已存在！',
	DGS_SOFTWARE_TITLE_ADD : '新增',
	DGS_SOFTWARE_TITLE_MODIFY : '修改',
	DGS_SOFTWARE_TITLE_CLASS : '软件分类',
	DGS_SOFTWARE_TITLE_SOFTWARE : '软件',
	DGS_SOFTWARE_TITLE_COPY : '复制',
	DGS_SOFTWARE_FIELD_NAME : '名称',
	DGS_SOFTWARE_FIELD_COPY_TO : '复制到',
	DGS_SOFTWARE_TIP_NOT_COPY_TO_SOFTWARE : '不可以复制到软件下！',
	DGS_SOFTWARE_TIP_NOT_COPY_TO_ROOT : '软件不可以复制到根节点下！',
	DGS_SOFTWARE_TIP_NOT_COPY_TO_SELF : '不可以复制到自己本身下！',
	DGS_SOFTWARE_TIP_COPY_NAME : '复制到同级目录下需要修改名称！',
	DGS_SOFTWARE_TITLE_ADD_PROCESS : '新增进程',
	DGS_SOFTWARE_TITLE_MODIFY_PROCESS : '修改进程',
	DGS_SOFTWARE_TITLE_VIEW_PROCESS : '查看进程',
	/*********************应用软件管理 end******************/
	
	/*********************加密策略模板 start******************/
	DG_SECURITY_POLICY_TEMPLATE : '加密策略模板',
	DG_SECURITY_POLICY_TEMPLATE_APPLY : '应用模板',
	DG_SECURITY_POLICY_TEMPLATE_SEARCH_TIP : '请输入名称',
	DG_SECURITY_POLICY_TEMPLATE_SEARCH_DG_TIP : '请输入终端名称或资产责任者',
	DG_SECURITY_POLICY_TEMPLATE_TEXT_NAME : '名称',
	DG_SECURITY_POLICY_TEMPLATE_TEXT_VERSION : '版本',
	DG_SECURITY_POLICY_TEMPLATE_TEXT_REMARK : '备注',
	DG_SECURITY_POLICY_TEMPLATE_SELECT_ONE : '请选择一个加密策略模板！',
	DG_SECURITY_POLICY_TEMPLATE_SELECT_ALL : '全选',
	DG_SECURITY_POLICY_TEMPLATE_APPLY_CHILD : '应用到子项',
	DG_SECURITY_POLICY_TEMPLATE_SEARCH_ALL : '查询全部',
	DG_SECURITY_POLICY_TEMPLATE_TEXT_APPLY : '是否应用',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_NAME : '模板名称',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_REMARK : '备注信息',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_KEY:'加解密槽',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_MODEL : '策略模式',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_SECURITY_MODEL : '加密模式',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_SMART_MODEL : '智能模式',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_SELF_MODEL : '个人模式',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_WHITE_LIST:'浏览器白名单',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_SCAN_ENCRYPTION : '扫描加密后缀',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_OFFLINETIME:'脱机时间（单位：小时）',
	DG_SECURITY_POLICY_TEMPLATE_TITLE_BASIC_INFO : '基本信息',
	DG_SECURITY_POLICY_TEMPLATE_TITLE_SOFTWARE : '支持软件类型',
	DG_SECURITY_POLICY_TEMPLATE_TITLE_SELFDEFINE : '其他设置',
	DG_SECURITY_POLICY_TEMPLATE_TITLE_BASIC_AUTH : '基本权限设置',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_COPY : '允许拷贝',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_PRINT : '允许打印',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_PRINT_SCREEN : '允许截屏',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_FTP_UPLOAD : '允许FTP上传',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_IE_COPY : '允许IE拷贝',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_RECOGNIZE : '标识加密文件',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_HACKER_SOFTWARE : '允许运行黑客软件',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_OFFLINE : '允许脱机',
	DG_SECURITY_POLICY_TEMPLATE_SELECT_ONE_SOFTWARE : '至少选择一个支持的软件类型！',
	DG_SECURITY_POLICY_TEMPLATE_TIP_EXIST : '该模板名称已存在！',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_USE_NET_REDIRECT : '端口重定向',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_PROCESS_NAME : '进程名',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_IS_SERVER : '服务进程',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_SRC_SERVER_PORT : '源端口号',
	DG_SECURITY_POLICY_TEMPLATE_FIELD_DETOURED_PORT : '目的端口号',
	DG_SECURITY_POLICY_TEMPLATE_PROCESS_NAME_NOT_NULL : '进程名称必填！',
	/*********************加密策略模板 end******************/
	
	/*********************外发策略模板 start******************/
	DG_FD_TEMPLATE : '外发策略模板',
	DG_FD_TEMPLATE_APPLY : '应用模板',
	DG_FD_TEMPLATE_SEARCH_TIP : '请输入名称',
	DG_FD_TEMPLATE_TEXT_NAME : '名称',
	DG_FD_TEMPLATE_TEXT_VERSION : '版本',
	DG_FD_TEMPLATE_SELECT_ONE : '请选择一个外发策略模板！',
	DG_FD_TEMPLATE_SELECT_ALL : '全选',
	DG_FD_TEMPLATE_APPLY_CHILD : '应用到子项',
	DG_FD_TEMPLATE_SEARCH_ALL : '查询全部',
	DG_FD_TEMPLATE_TEXT_APPLY : '是否应用',
	DG_FD_TEMPLATE_FIELD_NAME : '模板名称',
	DG_FD_TEMPLATE_FIELD_APPLY_GRADE : '申请等级',
	DG_FD_TEMPLATE_FIELD_APPLY_GRADE1 : '本地制作外发，不上传任何记录',
	DG_FD_TEMPLATE_FIELD_APPLY_GRADE2 : '本地制作外发，上传制作记录',
	DG_FD_TEMPLATE_FIELD_APPLY_GRADE3 : '本地制作外发，上传制作记录和文件',
	DG_FD_TEMPLATE_FIELD_APPLY_GRADE4 : '上传申请记录，后台制作外发',
	DG_FD_TEMPLATE_FIELD_APPLY_GRADE5 : '上传申请记录，后台制作外发并邮件发送',
	DG_FD_TEMPLATE_FIELD_AUTH : '外发文件权限',
	DG_FD_TEMPLATE_FIELD_AUTH1 : '明文',
	DG_FD_TEMPLATE_FIELD_AUTH2 : '密文',
	DG_FD_TEMPLATE_FIELD_DAYS : '有效天数',
	DG_FD_TEMPLATE_FIELD_TIMES : '有效次数',
	DG_FD_TEMPLATE_FIELD_OPERATION : '允许操作',
	DG_FD_TEMPLATE_FIELD_OPERATION1 : '打印',
	//DG_FD_TEMPLATE_FIELD_OPERATION2 : '截屏',
	DG_FD_TEMPLATE_FIELD_OPERATION3 : '拷贝',
	DG_FD_TEMPLATE_FIELD_WORKFLOW : '外发审批流程',
	DG_FD_TEMPLATE_SELECT_OPERATION : '请选择允许操作！',
	DG_FD_TEMPLATE_SELECT_WORKFLOW : '请选择外发审批流程！',
	DG_FD_TEMPLATE_TIP_EXIST : '该模板名称已存在！',
	DG_FD_TEMPLATE_FIELD_MAIL_SENDER : '发件人',
	DG_FD_TEMPLATE_FIELD_MAIL_SENDER1 : '系统账号',
	DG_FD_TEMPLATE_FIELD_MAIL_SENDER2 : '申请者账号',
	/*********************外发策略模板 end******************/
	
	/*********************数据字典 start******************/
	DGS_DICT_BUTTON_EDIT_ITME : '编辑值域',
	DGS_DICT_BUTTON_VIEW_ITME : '查看值域',
	DGS_DICT_TIPS_NAME : '请输入名称',
	DGS_DICT_TEXT_ATTRIBUTE : '属性',
	DGS_DICT_TEXT_NAME : '名称',
	DGS_DICT_TEXT_KEY : 'KEY',
	DGS_DICT_TEXT_VALUE : 'VALUE',
	DGS_DICT_TEXT_OPRATION : '操作',
	DGS_DICT_SELECT_ONE : '只能选择一个字典！',
	DGS_DICT_EXITS : '字典已存在！',
	/*********************数据字典 end******************/
	
	/*********************工作流定义 start******************/
	DGS_WORKFLOW_TIPS_NAME : '请输入工作流名称',
	DGS_WORKFLOW_TEXT_NAME : '工作流名称',
	DGS_WORKFLOW_SELECT_ONE : '只能选择一个工作流！',
	DGS_WORKFLOW_NODE_NAME : '节点名称',
	DGS_WORKFLOW_NODE_TYPE : '节点类型',
	DGS_WORKFLOW_NODE_TYPE1 : '普通',
	DGS_WORKFLOW_NODE_TYPE2 : '会签',
	DGS_WORKFLOW_NODE_WAY : '审批方式',
	DGS_WORKFLOW_NODE_WAY1 : '规则',
	DGS_WORKFLOW_NODE_WAY2 : '人员',
	DGS_WORKFLOW_NODE_JOBLEVEL : '岗级',
	DGS_WORKFLOW_BUTTON_SELECT_USER : '选择审批人',
	DGS_WORKFLOW_NODE_USER : '审批人',
	DGS_WORKFLOW_TIP_ONE_NODE : '至少定义一个流程节点！',
	DGS_WORKFLOW_TIP_NODE : '流程节点',
	DGS_WORKFLOW_TIP_NODE_JOBLEVEL : '必须选择岗级！',
	DGS_WORKFLOW_TIP_NODE_USER : '必须选择审批人！',
	DGS_WORKFLOW_EXITS : '该工作流名称已存在！',
	DGS_WORKFLOW_NODE_EXITS : '该工作流中已存在同名节点！',
	/*********************工作流定义 end******************/
	
	/*********************用户安全策略 start******************/
	DG_USER_POLICY_BUTTION_APPLY_DG : '应用加密策略',
	DG_USER_POLICY_BUTTION_APPLY_FD : '应用外发策略',
	DG_USER_POLICY_BUTTION_VIEW_DG : '查看加密策略',
	DG_USER_POLICY_BUTTION_VIEW_FD : '查看外发策略',
	DG_USER_POLICY_SEARCH_TIPS : '请输入名称',
	DG_USER_POLICY_TEXT_NAME : '名称',
	DG_USER_POLICY_TEXT_DG : '加密策略模板',
	DG_USER_POLICY_TEXT_FD : '外发策略模板',
	DG_USER_POLICY_SELECT_ONE : '只能选择一个用户或部门！',
	DG_USER_POLICY_NO_DG_TEMPLATE : '未应用加密策略模板！',
	DG_USER_POLICY_NO_FD_TEMPLATE : '未应用外发策略模板！',
	DG_USER_POLICY_APPLY_DG_TEMPLATE : '应用加密策略模板',
	DG_USER_POLICY_SELECT_DG_TEMPLATE : '请选择需要应用的加密策略模板！',
	DG_USER_POLICY_APPLY_FD_TEMPLATE : '应用外发策略模板',
	DG_USER_POLICY_SELECT_FD_TEMPLATE : '请选择需要应用的外发策略模板！',
	/*********************用户安全策略 end******************/
	
	/*********************外发单位管理 start******************/
	DG_FD_COMPANY_SEARCH_TIPS : '请输入单位名称',
	DG_FD_COMPANY_TEXT_NAME : '单位名称',
	DG_FD_COMPANY_TEXT_ADDRESS : '地址',
	DG_FD_COMPANY_TEXT_CONTACTS : '联系人',
	DG_FD_COMPANY_TEXT_PHONE : '电话',
	DG_FD_COMPANY_TEXT_EMAIL : '邮件',
	DG_FD_COMPANY_SELECT_ONE : '只能选择一个单位！',
	DG_FD_COMPANY_EXITS : '该单位已存在！',
	DG_FD_COMPANY_BUTTON_EDIT_EMAIL : '编辑邮箱',
	DG_FD_COMPANY_BUTTON_VIEW_EMAIL : '查看邮箱',
	DG_FD_COMPANY_EDIT_EMAIL_NAME : '姓名',
	DG_FD_COMPANY_EDIT_EMAIL_EMAIL : '邮箱账号',
	DG_FD_COMPANY_BUTTON_MODIFY_EMAIL : '修改邮箱',
	DG_FD_COMPANY_BUTTON_ADD_EMAIL : '新增邮箱',
	DG_FD_COMPANY_EMAIL_EXIST : '该邮箱账号已存在！',
	DG_FD_COMPANY_SELECT_ONE_EMAIL : '只能选择一个邮箱！',
	/*********************外发单位管理 end******************/
	
	/*********************外发文件记录 start******************/
	DG_FD_RECORD_SEARCH_COMPANY : '接收单位',
	DG_FD_RECORD_SEARCH_APPLY_NAME : '申请人',
	DG_FD_RECORD_SEARCH_APPROVER_NAME : '审批人',
	DG_FD_RECORD_SEARCH_STATUS : '状态',
	DG_FD_RECORD_SEARCH_DEPT : '部门',
	DG_FD_RECORD_SEARCH_APPLY_GRADE : '申请等级',
	DG_FD_RECORD_SEARCH_START_TIME : '起始日期',
	DG_FD_RECORD_SEARCH_END_TIME : '截止日期',
	DG_FD_RECORD_BUTTON_VIEW : '查看详情',
	DG_FD_RECORD_TEXT_CREATOR_TIME : '申请时间',
	DG_FD_RECORD_TEXT_COMPANY_NAME : '接收单位',
	DG_FD_RECORD_TEXT_APPLY_NAME : '申请人',
	DG_FD_RECORD_TEXT_APPLY_GRADE : '申请等级',
	DG_FD_RECORD_TEXT_DEPT : '所属部门',
	DG_FD_RECORD_TEXT_STATUS : '状态',
	DG_FD_RECORD_TEXT_APPROVER_NAME : '当前审批人',
	DG_FD_RECORD_APPLY_INFO : '申请信息',
	DG_FD_RECORD_DOC_LIST : '文件列表',
	DG_FD_RECORD_APPROVAL_INFO : '审批记录',
	DG_FD_RECORD_FIELD_COMPANY_NAME : '接收单位',
	DG_FD_RECORD_FIELD_FD_AUTH : '外发文件权限',
	DG_FD_RECORD_FIELD_REMARK : '申请意见',
	DG_FD_RECORD_PLAINTEXT : '明文',
	DG_FD_RECORD_CIPHERTEXT : '密文',
	DG_FD_RECORD_DAYS : '有效天数',
	DG_FD_RECORD_TIMES : '有效次数',
	DG_FD_RECORD_DOC_NAME : '名称',
	DG_FD_RECORD_DOC_STATUS : '状态',
	DG_FD_RECORD_DOC_OPRATION : '操作',
	DG_FD_RECORD_APPROVER_NAME : '审批人',
	DG_FD_RECORD_APPROVER_TIME : '审批时间',
	DG_FD_RECORD_APPROVER_STATUS : '审批状态',
	DG_FD_RECORD_APPROVER_STATUS1 : '待审批',
	DG_FD_RECORD_APPROVER_STATUS2 : '审批通过',
	DG_FD_RECORD_APPROVER_STATUS3 : '不通过',
	DG_FD_RECORD_APPROVER_REMARK : '审批原因',
	DG_FD_RECORD_NODE_GRADE : '节点等级',
	DG_FD_RECORD_DATE_ERROR : '起始日期不能大于截止日期！',
	DG_FD_RECORD_STATUS1 : '审批中',
	DG_FD_RECORD_STATUS2 : '审批完成',
	DG_FD_RECORD_STATUS3 : '审批驳回',
	DG_FD_RECORD_STATUS4 : '制作中',
	DG_FD_RECORD_STATUS5 : '完成',
	DG_FD_RECORD_STATUS6 : '制作失败',
	DG_FD_RECORD_SELECT_ERROR : '请选择待审批的记录！',
	DG_FD_RECORD_START_TIME : '申请开始日期',
	DG_FD_RECORD_END_TIME : '申请截止日期',
	DG_FD_RECORD_BUTTON_REGISTER : '审批',
	DG_FD_RECORD_BUTTON_ENTRUST : '委托',
	DG_FD_RECORD_BUTTON_CANCEL_ENTRUST : '取消委托',
	DG_FD_RECORD_IS_CANCEL_ENTRUST : '是否确认取消委托？',
	DG_FD_RECORD_TITLE_REGISTER : '审批',
	DG_FD_RECORD_APPLY_INFO : '申请信息',
	DG_FD_RECORD_DOC_LIST　: '申请列表',
	DG_FD_RECORD_APPROVAL_INFO : '审计信息',
	DG_FD_RECORD_APPLY_REASON : '申请原因',
	DG_FD_RECORD_APPROVAL_REASON : '您的意见',
	DG_FD_RECORD_BUTTON_AGREE : '同意',
	DG_FD_RECORD_BUTTON_DISAGREE : '驳回',
	DG_FD_RECORD_WORKFLOW_ERROR : '审批流程有误，异常结束！',
	DG_FD_RECORD_BUTTON_NO_APPROVER : '没有合适的审批人',
	DG_FD_RECORD_SELECT_APPROVER : '选择审批人',
	DG_FD_RECORD_NEXT_APPROVER : '下一审批人',
	DG_FD_RECORD_SELECT_ENTRUST : '选择委托人',
	DG_FD_RECORD_ENTRUST : '受委托人',
	DG_FD_RECORD : '外发记录',
	DG_FD_RECORD_APPLY : '申请记录',
	DG_FD_RECORD_APPROVE : '审批记录',
	DG_FD_RECORD_BUTTON_REMAKE_DOC : '重新制作',
	/*********************外发文件记录 end******************/
	
	/*********************各首页统计 start******************/
	DGS_WELCOME_FIRST_PAGE : '首页',
	DGS_WELCOME_BUTTON_REFRESH : '刷新数据',
	DGS_WELCOME_TITLE_ONLINE_TERMINAL : '终端在线率',
	DGS_WELCOME_TITLE_TERMINAL_INFO : '终端版本信息',
	DGS_WELCOME_TITLE_DG_TEMPLATE : '加密策略模板使用数',
	DGS_WELCOME_TITLE_FD_TEMPLATE : '外发策略模板使用数',
	DGS_WELCOME_TITLE_USER_FD : '用户外发量',
	DGS_WELCOME_TITLE_COMPANY_FD : '单位外发量',
	DGS_WELCOME_TITLE_DAY_FD : '每天外发量',
	DGS_WELCOME_TITLE_FOLDER_TYPE : '文件夹类型的文件量',
	DGS_WELCOME_TITLE_DOC_TYPE : '文件类型的文件量',
	DGS_WELCOME_TITLE_USER_UPLOAD : '用户上传量',
	DGS_WELCOME_TITLE_DOC_DOWNLOAD : '文件下载量',
	DGS_WELCOME_TITLE_DOC_PREVIEW : '文件预览量',
	DGS_WELCOME_TITLE_CLASSIC_DOCUMENT : '文件库每天文件量',
	DGS_WELCOME_LEGEND_DOC_COUNT : '文件量(个)',
	DGS_WELCOME_LEGEND_DOC_SIZE : '文件大小(M)',
	DGS_WELCOME_TITLE_SECURITY : '密级文件量',
	/*********************各首页统计 end******************/
	
	/*********************归档流程配置 start******************/
	DM_FILING_FLOW_BUTTON_SET : '配置归档流程',
	DM_FILING_FLOW_BUTTON_VIEW : '查看归档流程',
	DM_FILING_FLOW_BUTTON_CANCEL : '取消归档流程',
	DM_FILING_FLOW_SEARCH_NAME : '请输入名称',
	DM_FILING_FLOW_NAME : '归档流程',
	DM_FILING_FLOW_NO_NAME : '未分配归档流程！',
	DM_FILING_FLOW_SELECT : '请选择归档流程！',
	/*********************归档流程配置 end******************/
	
	/*********************元数据模板管理 start******************/
	DM_META_DATA_BUTTON_EDIT_ITME : '编辑元数据',
	DM_META_DATA_BUTTON_VIEW_ITME : '查看元数据',
	DM_META_DATA_SEARCH_NAME : '请输入名称',
	DM_META_DATA_NAME : '模板名称',
	DM_META_DATA_REMARK : '备注',
	DM_META_DATA_SELECT_ONE : '只能选择一个模板！',
	DM_META_DATA_SELECT_ONE_META : '只能选择一个元数据！',
	DM_META_DATA_MODIFY : '修改元数据',
	DM_META_DATA_ADD : '新增元数据',
	DM_META_DATA_META_NAME : '名称',
	DM_META_DATA_META_ATTRIBUTE : '属性',
	DM_META_DATA_META_ATTRIBUTE_TIPS : '属性只能包含数字和字母！',
	DM_META_DATA_META_ATTRIBUTE_TIPS1 : '特殊属性名，与系统字段冲突，请修改！',
	DM_META_DATA_LENGTH : '字段长度',
	DM_META_DATA_LENGTH_TIPS : '字段长度不可以改短！',
	DM_META_DATA_TYPE : '类型',
	DM_META_DATA_TYPE1 : '普通文本',
	DM_META_DATA_TYPE2 : '下拉框',
	DM_META_DATA_VALUE_FIELD : '值域',
	DM_META_DATA_VALUE_FIELD_EMPTY_TIP : '以英文逗号分隔，如：男,女',
	DM_META_DATA_VALUE_FIELD_TIPS : '下拉框类型请填写值域！',
	DM_META_DATA_META_ATTRIBUTE_EXIST : '该元数据属性已存在！',
	DM_META_DATA_META_NAME_EXIST : '该元数据名称已存在！',
	DM_META_DATA_EXIST : '该模板名称已存在！',
	DM_META_DATA_ADD_RECORD : '新增记录',
	DM_META_DATA_MODIFY_RECORD : '修改记录',
	DM_META_DATA_RECORD_NAME : '名称',
	DM_META_DATA_RECORD_TEMPLATE : '元数据模板',
	DM_META_DATA_RECORD_SELECT_ERROR : '请选择有元数据的模板！',
	DM_META_DATA_TEMPLATE_USED : '模板已被使用，不可删除！'
	/*********************元数据模板管理 end******************/
}



